# Generated by Django 5.1.15 on 2026-06-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('razon_social', models.CharField(max_length=450, verbose_name='razón social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=450, verbose_name='nombre comercial')),
                ('numero_identificacion', models.CharField(help_text='NIT sin puntos, sin guiones y sin dígito de verificación.', max_length=20, verbose_name='número de identificación')),
                ('digito_verificacion', models.CharField(blank=True, max_length=1, verbose_name='dígito de verificación')),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emisores', to='catalogos.departamento', verbose_name='departamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emisores', to='catalogos.municipio', verbose_name='municipio')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emisores', to='catalogos.pais', verbose_name='país')),
                ('responsabilidades', models.ManyToManyField(blank=True, related_name='emisores', to='catalogos.responsabilidadfiscal', verbose_name='responsabilidades fiscales')),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emisores', to='catalogos.tipoidentificacion', verbose_name='tipo de identificación')),
                ('tipo_organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emisores', to='catalogos.tipoorganizacion', verbose_name='tipo de organización')),
            ],
            options={
                'verbose_name': 'emisor',
                'verbose_name_plural': 'emisores',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('alias', models.CharField(blank=True, max_length=150, verbose_name='alias')),
                ('archivo', models.FileField(upload_to='certificados/', verbose_name='archivo .p12')),
                ('clave', models.CharField(max_length=255, verbose_name='clave del certificado')),
                ('vigente_desde', models.DateField(blank=True, null=True, verbose_name='vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, null=True, verbose_name='vigente hasta')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='emisores.emisor', verbose_name='emisor')),
            ],
            options={
                'verbose_name': 'certificado digital',
                'verbose_name_plural': 'certificados digitales',
            },
        ),
        migrations.CreateModel(
            name='ResolucionFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('numero_resolucion', models.CharField(max_length=50, verbose_name='número de resolución')),
                ('fecha_resolucion', models.DateField(verbose_name='fecha de la resolución')),
                ('prefijo', models.CharField(blank=True, max_length=10, verbose_name='prefijo')),
                ('rango_desde', models.PositiveBigIntegerField(verbose_name='rango desde')),
                ('rango_hasta', models.PositiveBigIntegerField(verbose_name='rango hasta')),
                ('clave_tecnica', models.CharField(blank=True, max_length=255, verbose_name='clave técnica')),
                ('vigente_desde', models.DateField(verbose_name='vigente desde')),
                ('vigente_hasta', models.DateField(verbose_name='vigente hasta')),
                ('consecutivo_actual', models.PositiveBigIntegerField(default=0, help_text='Último consecutivo emitido; 0 si aún no se ha emitido.', verbose_name='consecutivo actual')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='emisores.emisor', verbose_name='emisor')),
                ('tipo_factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resoluciones', to='catalogos.tipofactura', verbose_name='tipo de factura')),
            ],
            options={
                'verbose_name': 'resolución de facturación',
                'verbose_name_plural': 'resoluciones de facturación',
                'ordering': ['-fecha_resolucion'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareDian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('identificador', models.CharField(help_text='SoftwareID asignado por la DIAN.', max_length=100, verbose_name='ID del software')),
                ('pin', models.CharField(max_length=100, verbose_name='PIN del software')),
                ('id_proveedor', models.CharField(help_text='ProviderID: NIT del proveedor del software (sin DV).', max_length=20, verbose_name='ID del proveedor')),
                ('test_set_id', models.CharField(blank=True, help_text='TestSetId entregado por la DIAN para la habilitación.', max_length=100, verbose_name='ID del set de pruebas')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='emisores.emisor', verbose_name='emisor')),
            ],
            options={
                'verbose_name': 'software DIAN',
                'verbose_name_plural': 'softwares DIAN',
            },
        ),
        migrations.AddConstraint(
            model_name='emisor',
            constraint=models.UniqueConstraint(fields=('tipo_identificacion', 'numero_identificacion'), name='emisor_identificacion_unica'),
        ),
        migrations.AddConstraint(
            model_name='resolucionfacturacion',
            constraint=models.UniqueConstraint(fields=('emisor', 'tipo_factura', 'prefijo', 'numero_resolucion'), name='resolucion_unica_por_emisor'),
        ),
    ]
