# Generated by Django 5.1.15 on 2026-09-08 19:58

import apps.emisores.models.certificado
import apps.emisores.models.emisor
import apps.utilidades.almacenamiento
import apps.utilidades.cifrado
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('alias', models.CharField(blank=True, max_length=150, verbose_name='alias')),
                ('archivo', models.FileField(storage=apps.utilidades.almacenamiento.almacenamiento_backblaze, upload_to=apps.emisores.models.certificado.ruta_certificado, verbose_name='archivo .p12')),
                ('clave', apps.utilidades.cifrado.ClaveCifradaField(max_length=512, verbose_name='clave del certificado')),
                ('vigente_desde', models.DateField(blank=True, null=True, verbose_name='vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, null=True, verbose_name='vigente hasta')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'certificado digital',
                'verbose_name_plural': 'certificados digitales',
                'db_table': 'emi_certificado',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('numero_resolucion', models.CharField(max_length=50, verbose_name='número de resolución')),
                ('fecha_resolucion', models.DateField(verbose_name='fecha de la resolución')),
                ('prefijo', models.CharField(blank=True, max_length=10, verbose_name='prefijo')),
                ('rango_desde', models.PositiveBigIntegerField(verbose_name='rango desde')),
                ('rango_hasta', models.PositiveBigIntegerField(verbose_name='rango hasta')),
                ('clave_tecnica', models.CharField(blank=True, max_length=255, verbose_name='clave técnica')),
                ('vigente_desde', models.DateField(verbose_name='vigente desde')),
                ('vigente_hasta', models.DateField(verbose_name='vigente hasta')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'resolución',
                'verbose_name_plural': 'resoluciones',
                'db_table': 'emi_resolucion',
                'ordering': ['-fecha_resolucion'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareDian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('tipo', models.CharField(choices=[('facturacion', 'Facturación electrónica'), ('nomina', 'Nómina electrónica'), ('documento_equivalente', 'Documento equivalente electrónico')], help_text='Operación que habilita: facturación, nómina electrónica o documento equivalente.', max_length=25, verbose_name='tipo de software')),
                ('identificador', models.CharField(help_text='SoftwareID asignado por la DIAN.', max_length=100, verbose_name='ID del software')),
                ('pin', models.CharField(max_length=100, verbose_name='PIN del software')),
                ('test_set_id', models.CharField(blank=True, help_text='TestSetId entregado por la DIAN para la habilitación.', max_length=100, verbose_name='ID del set de pruebas')),
                ('set_pruebas_aceptado', models.BooleanField(default=False, help_text='Cuando la DIAN acepta el Set de Pruebas, los envíos pasan a SendBillSync (síncrono) en vez de SendTestSetAsync.', verbose_name='set de pruebas aceptado')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('codigo_proveedor_tecnologico', models.CharField(blank=True, help_text='Los tres dígitos que la DIAN asigna al proveedor tecnológico. Van en el nombre de todos los archivos del documento equivalente (numeral 8.13.5); con software propio suele ser 000.', max_length=3, verbose_name='código del PT')),
                ('fabricante_nombre', models.CharField(blank=True, help_text='Par `NombreApellido`. Vacío usa DIAN_FABRICANTE_NOMBRE.', max_length=200, verbose_name='nombre y apellido del fabricante')),
                ('fabricante_razon_social', models.CharField(blank=True, help_text='Par `RazonSocial`. Vacío usa DIAN_FABRICANTE_RAZON_SOCIAL. No es la razón social del emisor.', max_length=200, verbose_name='razón social del fabricante')),
                ('fabricante_nombre_software', models.CharField(blank=True, help_text='Par `NombreSoftware`. Vacío usa DIAN_FABRICANTE_NOMBRE_SOFTWARE.', max_length=200, verbose_name='nombre del software')),
            ],
            options={
                'verbose_name': 'software DIAN',
                'verbose_name_plural': 'softwares DIAN',
                'db_table': 'emi_software',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('razon_social', models.CharField(max_length=450, verbose_name='razón social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=450, verbose_name='nombre comercial')),
                ('numero_identificacion', models.CharField(help_text='NIT sin puntos, sin guiones y sin dígito de verificación.', max_length=20, verbose_name='número de identificación')),
                ('digito_verificacion', models.CharField(blank=True, max_length=1, verbose_name='dígito de verificación')),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección')),
                ('correo_copia', models.CharField(blank=True, help_text='Copia de las notificaciones al adquiriente. Varios correos separados por punto y coma. Vacío = no se envía copia.', max_length=255, verbose_name='correo en copia')),
                ('codigo_postal', models.CharField(blank=True, help_text='cbc:PostalZone de las direcciones del XML.', max_length=10, verbose_name='código postal')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('habilitado_facturacion', models.BooleanField(default=False, help_text='Se marca al enviar el Set de Pruebas a la DIAN. Es el paso que separa al emisor recién dado de alta del que ya salió a producción.', verbose_name='habilitado para facturar')),
                ('habilitado_nomina', models.BooleanField(default=False, help_text="La nómina se habilita aparte de la facturación y sin Set de Pruebas: el trámite es en el portal de la DIAN, así que esta bandera no la marca el sistema por sí solo. Sin ella, la DIAN rechaza con la regla 92 ('El Emisor del Documento no se encuentra Habilitado').", verbose_name='habilitado para nómina')),
                ('habilitado_documento_equivalente', models.BooleanField(default=False, help_text='El documento equivalente P.O.S. sí tiene Set de Pruebas propio (`SendTestSetAsync`), con su TestSetId: la DIAN exige emitir los documentos y las notas de ajuste que pida el sistema antes de pasar a producción.', verbose_name='habilitado para documento equivalente')),
                ('ambiente_facturacion', models.PositiveSmallIntegerField(choices=[(1, 'Producción'), (2, 'Habilitación')], default=apps.emisores.models.emisor.ambiente_por_defecto, help_text='Contra qué servidor de la DIAN salen las facturas, notas y documentos soporte de este emisor. Es por emisor y no del despliegue: unos pueden seguir en habilitación mientras otros ya están en producción.', verbose_name='ambiente DIAN de facturación')),
                ('ambiente_nomina', models.PositiveSmallIntegerField(choices=[(1, 'Producción'), (2, 'Habilitación')], default=apps.emisores.models.emisor.ambiente_por_defecto, help_text='Lo mismo para la nómina, que la DIAN habilita aparte: el mismo emisor puede estar en producción para factura y todavía en habilitación para nómina.', verbose_name='ambiente DIAN de nómina')),
                ('ambiente_documento_equivalente', models.PositiveSmallIntegerField(choices=[(1, 'Producción'), (2, 'Habilitación')], default=apps.emisores.models.emisor.ambiente_por_defecto, help_text='Y lo mismo para el documento equivalente P.O.S., que tiene su propia habilitación (Res. 000165/2023, numeral 4). Son tres ambientes independientes, no uno del despliegue.', verbose_name='ambiente DIAN de documento equivalente')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emisores', to='catalogos.departamento', verbose_name='departamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emisores', to='catalogos.municipio', verbose_name='municipio')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emisores', to='catalogos.pais', verbose_name='país')),
                ('responsabilidades', models.ManyToManyField(blank=True, related_name='emisores', to='catalogos.responsabilidadfiscal', verbose_name='responsabilidades fiscales')),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emisores', to='catalogos.tipoidentificacion', verbose_name='tipo de identificación')),
                ('tipo_organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emisores', to='catalogos.tipoorganizacion', verbose_name='tipo de organización')),
            ],
            options={
                'verbose_name': 'emisor',
                'verbose_name_plural': 'emisores',
                'db_table': 'emi_emisor',
                'ordering': ['razon_social'],
            },
        ),
    ]
