# Generated by Django 5.1.15 on 2026-09-08 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('emisores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario dueño del emisor.', on_delete=django.db.models.deletion.PROTECT, related_name='emisores_propios', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='emisores.emisor', verbose_name='emisor'),
        ),
        migrations.AddField(
            model_name='resolucion',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='emisores.emisor', verbose_name='emisor'),
        ),
        migrations.AddField(
            model_name='resolucion',
            name='tipo_factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resoluciones', to='catalogos.tipofactura', verbose_name='tipo de factura'),
        ),
        migrations.AddField(
            model_name='softwaredian',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='emisores.emisor', verbose_name='emisor'),
        ),
        migrations.AddConstraint(
            model_name='emisor',
            constraint=models.UniqueConstraint(fields=('tipo_identificacion', 'numero_identificacion'), name='emisor_identificacion_unica'),
        ),
        migrations.AddConstraint(
            model_name='resolucion',
            constraint=models.UniqueConstraint(fields=('emisor', 'tipo_factura', 'prefijo', 'numero_resolucion'), name='resolucion_unica_por_emisor'),
        ),
    ]
