# Generated by Django 5.1.15 on 2026-06-24 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        ('emisores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='emisores', to='cuentas.cuenta', verbose_name='cuenta'),
            preserve_default=False,
        ),
    ]
