# Generated by Django 5.1.15 on 2026-09-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emisor',
            name='nombre_comercial',
        ),
    ]
