# Generated by Django 5.1.15 on 2026-06-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0002_emisor_cuenta'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='certificadodigital',
            table='emi_certificadodigital',
        ),
        migrations.AlterModelTable(
            name='emisor',
            table='emi_emisor',
        ),
        migrations.AlterModelTable(
            name='resolucionfacturacion',
            table='emi_resolucionfacturacion',
        ),
        migrations.AlterModelTable(
            name='softwaredian',
            table='emi_softwaredian',
        ),
    ]
