# Generated by Django 5.1.15 on 2026-06-26 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0003_alter_certificadodigital_table_alter_emisor_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='softwaredian',
            table='emi_software',
        ),
    ]
