# Generated by Django 5.1.15 on 2026-06-27 00:04

import apps.utilidades.almacenamiento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0004_alter_softwaredian_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadodigital',
            name='archivo',
            field=models.FileField(storage=apps.utilidades.almacenamiento.almacenamiento_backblaze, upload_to='certificados/', verbose_name='archivo .p12'),
        ),
    ]
