# Generated by Django 5.1.15 on 2026-09-16 15:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0005_software_unico_por_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('url', models.URLField(max_length=500, validators=[django.core.validators.URLValidator(message='Tiene que ser una URL HTTPS válida (https://…).', schemes=['https'])], verbose_name='URL')),
                ('estado_validado', models.BooleanField(default=False, verbose_name='avisar la validación')),
                ('estado_notificado', models.BooleanField(default=False, verbose_name='avisar la notificación')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='emisores.emisor', verbose_name='emisor')),
            ],
            options={
                'verbose_name': 'webhook',
                'verbose_name_plural': 'webhooks',
                'db_table': 'emi_webhook',
                'ordering': ['-creado_en'],
            },
        ),
    ]
