# Generated by Django 5.1.15 on 2026-06-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0005_alter_certificadodigital_archivo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='certificadodigital',
            table='emi_certificado',
        ),
    ]
