# Generated by Django 5.1.15 on 2026-06-27 13:40

import apps.emisores.models.certificado
import apps.utilidades.almacenamiento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0006_alter_certificadodigital_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadodigital',
            name='archivo',
            field=models.FileField(storage=apps.utilidades.almacenamiento.almacenamiento_backblaze, upload_to=apps.emisores.models.certificado.ruta_certificado, verbose_name='archivo .p12'),
        ),
    ]
