# Generated by Django 5.1.15 on 2026-09-22 07:34

import apps.utilidades.cifrado
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0006_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='secreto',
            field=apps.utilidades.cifrado.ClaveCifradaField(blank=True, llave='WEBHOOK_ENCRYPTION_KEY', max_length=512, verbose_name='secreto'),
        ),
    ]
