# Generated by Django 5.1.15 on 2026-06-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0007_alter_certificadodigital_archivo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CertificadoDigital',
            new_name='Certificado',
        ),
    ]
