# Generated by Django 5.1.15 on 2026-09-22 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_eventos'),
        ('emisores', '0007_webhook_secreto'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='referencia_externa',
            field=models.CharField(blank=True, help_text='Identificador del emisor en el sistema que lo integra (en torio, el id del cliente). Viaja como `cliente` en los avisos de webhook; sin él no se envían.', max_length=100, verbose_name='referencia externa'),
        ),
        migrations.CreateModel(
            name='WebhookAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('validacion', 'Validación de la DIAN'), ('notificacion', 'Notificación al adquiriente')], max_length=20, verbose_name='tipo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('fallido', 'Fallido')], default='pendiente', max_length=20, verbose_name='estado')),
                ('cuerpo', models.TextField(verbose_name='cuerpo')),
                ('codigo_http', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='código HTTP')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('enviado_en', models.DateTimeField(blank=True, null=True, verbose_name='enviado en')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_webhook', to='documentos.documento', verbose_name='documento')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='emisores.webhook', verbose_name='webhook')),
            ],
            options={
                'verbose_name': 'aviso de webhook',
                'verbose_name_plural': 'avisos de webhook',
                'db_table': 'emi_webhook_aviso',
                'ordering': ['-creado_en', '-id'],
            },
        ),
    ]
