# Generated by Django 5.1.15 on 2026-06-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0008_rename_certificadodigital_certificado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resolucionfacturacion',
            table='emi_resolucion_facturacion',
        ),
    ]
