# Generated by Django 5.1.15 on 2026-09-22 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0008_webhook_aviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.URLField(max_length=500, validators=[django.core.validators.URLValidator(message='Tiene que ser una URL http:// o https:// válida.', schemes=['http', 'https'])], verbose_name='URL'),
        ),
    ]
