# Generated by Django 5.1.15 on 2026-06-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0009_alter_resolucionfacturacion_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwaredian',
            name='set_pruebas_aceptado',
            field=models.BooleanField(default=False, help_text='Cuando la DIAN acepta el Set de Pruebas, los envíos pasan a SendBillSync (síncrono) en vez de SendTestSetAsync.', verbose_name='set de pruebas aceptado'),
        ),
    ]
