# Generated by Django 5.1.15 on 2026-10-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0010_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwaredian',
            name='modulo',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(then=models.Value('nomina'), tipo='nomina'), default=models.Value('facturacion')), output_field=models.CharField(choices=[('facturacion', 'Facturación'), ('nomina', 'Nómina')], max_length=15, verbose_name='módulo')),
        ),
    ]
