# Generated by Django 5.1.15 on 2026-10-10 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_eventos_radian_y_festivos'),
        ('emisores', '0011_software_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='acuse_automatico',
            field=models.BooleanField(default=False, help_text='Emite el 030 solo, cuando una factura recibida se verifica como válida ante la DIAN. Apagado por defecto: lo enciende el emisor. Necesita la persona que recibe.', verbose_name='acuse de recibo automático'),
        ),
        migrations.AddField(
            model_name='emisor',
            name='recibe_apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='apellidos de quien recibe'),
        ),
        migrations.AddField(
            model_name='emisor',
            name='recibe_area',
            field=models.CharField(blank=True, max_length=100, verbose_name='área de quien recibe'),
        ),
        migrations.AddField(
            model_name='emisor',
            name='recibe_cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='cargo de quien recibe'),
        ),
        migrations.AddField(
            model_name='emisor',
            name='recibe_nombres',
            field=models.CharField(blank=True, max_length=100, verbose_name='nombres de quien recibe'),
        ),
        migrations.AddField(
            model_name='emisor',
            name='recibe_numero_identificacion',
            field=models.CharField(blank=True, max_length=20, verbose_name='identificación de quien recibe'),
        ),
        migrations.AddField(
            model_name='emisor',
            name='recibe_tipo_identificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.tipoidentificacion', verbose_name='tipo de identificación de quien recibe'),
        ),
    ]
