# Generated by Django 5.1.15 on 2026-08-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0011_emisor_identificacion_unica_por_cuenta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['-creado_en'], 'verbose_name': 'certificado digital', 'verbose_name_plural': 'certificados digitales'},
        ),
        migrations.AlterModelOptions(
            name='softwaredian',
            options={'ordering': ['-creado_en'], 'verbose_name': 'software DIAN', 'verbose_name_plural': 'softwares DIAN'},
        ),
    ]
