# Generated by Django 5.1.15 on 2026-08-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0012_alter_certificado_options_alter_softwaredian_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwaredian',
            name='id_proveedor',
        ),
    ]
