# Generated by Django 5.1.15 on 2026-08-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0013_remove_softwaredian_id_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='habilitado_facturacion',
            field=models.BooleanField(default=False, help_text='Se marca al enviar el Set de Pruebas a la DIAN. Es el paso que separa al emisor recién dado de alta del que ya salió a producción.', verbose_name='habilitado para facturar'),
        ),
    ]
