# Generated by Django 5.1.15 on 2026-08-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0016_emisor_codigo_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='codigo_interface',
            field=models.CharField(blank=True, help_text='Identifica al emisor ante los servicios externos; se envía como `operador` en los correos de la pasarela Zinc.', max_length=30, verbose_name='código de interface'),
        ),
    ]
