# Generated by Django 5.1.15 on 2026-08-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0017_emisor_codigo_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='correo_copia',
            field=models.CharField(blank=True, help_text='Copia de las notificaciones al adquiriente. Varios correos separados por punto y coma. Vacío = no se envía copia.', max_length=255, verbose_name='correo en copia'),
        ),
    ]
