# Generated by Django 5.1.15 on 2026-08-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0018_emisor_correo_copia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emisor',
            name='codigo_interface',
        ),
    ]
