# Generated by Django 5.1.15 on 2026-08-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0020_rename_resolucionfacturacion_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='habilitado_nomina',
            field=models.BooleanField(default=False, help_text="La nómina se habilita aparte de la facturación y sin Set de Pruebas: el trámite es en el portal de la DIAN, así que esta bandera no la marca el sistema por sí solo. Sin ella, la DIAN rechaza con la regla 92 ('El Emisor del Documento no se encuentra Habilitado').", verbose_name='habilitado para nómina'),
        ),
    ]
