# Generated by Django 5.1.15 on 2026-08-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0021_emisor_habilitado_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwaredian',
            name='tipo',
            field=models.CharField(choices=[('facturacion', 'Facturación electrónica'), ('nomina', 'Nómina electrónica')], default='facturacion', help_text='Operación que habilita: facturación o nómina electrónica.', max_length=20, verbose_name='tipo de software'),
            preserve_default=False,
        ),
    ]
