# Generated by Django 5.1.15 on 2026-08-28 08:04

import apps.emisores.models.emisor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0022_softwaredian_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='ambiente_facturacion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Producción'), (2, 'Habilitación')], default=apps.emisores.models.emisor.ambiente_por_defecto, help_text='Contra qué servidor de la DIAN salen las facturas, notas y documentos soporte de este emisor. Es por emisor y no del despliegue: unos pueden seguir en habilitación mientras otros ya están en producción.', verbose_name='ambiente DIAN de facturación'),
        ),
        migrations.AddField(
            model_name='emisor',
            name='ambiente_nomina',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Producción'), (2, 'Habilitación')], default=apps.emisores.models.emisor.ambiente_por_defecto, help_text='Lo mismo para la nómina, que la DIAN habilita aparte: el mismo emisor puede estar en producción para factura y todavía en habilitación para nómina.', verbose_name='ambiente DIAN de nómina'),
        ),
    ]
