# Generated by Django 5.1.15 on 2026-08-31 10:00

import apps.emisores.models.emisor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0023_emisor_ambiente_facturacion_emisor_ambiente_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='ambiente_documento_equivalente',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Producción'), (2, 'Habilitación')], default=apps.emisores.models.emisor.ambiente_por_defecto, help_text='Y lo mismo para el documento equivalente P.O.S., que tiene su propia habilitación (Res. 000165/2023, numeral 4). Son tres ambientes independientes, no uno del despliegue.', verbose_name='ambiente DIAN de documento equivalente'),
        ),
        migrations.AddField(
            model_name='emisor',
            name='habilitado_documento_equivalente',
            field=models.BooleanField(default=False, help_text='El documento equivalente P.O.S. sí tiene Set de Pruebas propio (`SendTestSetAsync`), con su TestSetId: la DIAN exige emitir los documentos y las notas de ajuste que pida el sistema antes de pasar a producción.', verbose_name='habilitado para documento equivalente'),
        ),
        migrations.AddField(
            model_name='softwaredian',
            name='codigo_proveedor_tecnologico',
            field=models.CharField(blank=True, help_text='Los tres dígitos que la DIAN asigna al proveedor tecnológico. Van en el nombre de todos los archivos del documento equivalente (numeral 8.13.5); con software propio suele ser 000.', max_length=3, verbose_name='código del PT'),
        ),
        migrations.AddField(
            model_name='softwaredian',
            name='fabricante_nombre',
            field=models.CharField(blank=True, help_text='Par `NombreApellido` de la extensión del fabricante.', max_length=200, verbose_name='nombre y apellido del fabricante'),
        ),
        migrations.AddField(
            model_name='softwaredian',
            name='fabricante_nombre_software',
            field=models.CharField(blank=True, help_text='Par `NombreSoftware` de la extensión del fabricante.', max_length=200, verbose_name='nombre del software'),
        ),
        migrations.AddField(
            model_name='softwaredian',
            name='fabricante_razon_social',
            field=models.CharField(blank=True, help_text='Par `RazonSocial` de la extensión del fabricante.', max_length=200, verbose_name='razón social del fabricante'),
        ),
        migrations.AlterField(
            model_name='softwaredian',
            name='tipo',
            field=models.CharField(choices=[('facturacion', 'Facturación electrónica'), ('nomina', 'Nómina electrónica'), ('documento_equivalente', 'Documento equivalente electrónico')], help_text='Operación que habilita: facturación, nómina electrónica o documento equivalente.', max_length=25, verbose_name='tipo de software'),
        ),
    ]
