# Generated by Django 5.1.15 on 2026-09-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0024_documento_equivalente_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwaredian',
            name='fabricante_nombre',
            field=models.CharField(blank=True, help_text='Par `NombreApellido`. Vacío usa DIAN_FABRICANTE_NOMBRE.', max_length=200, verbose_name='nombre y apellido del fabricante'),
        ),
        migrations.AlterField(
            model_name='softwaredian',
            name='fabricante_nombre_software',
            field=models.CharField(blank=True, help_text='Par `NombreSoftware`. Vacío usa DIAN_FABRICANTE_NOMBRE_SOFTWARE.', max_length=200, verbose_name='nombre del software'),
        ),
        migrations.AlterField(
            model_name='softwaredian',
            name='fabricante_razon_social',
            field=models.CharField(blank=True, help_text='Par `RazonSocial`. Vacío usa DIAN_FABRICANTE_RAZON_SOCIAL. No es la razón social del emisor.', max_length=200, verbose_name='razón social del fabricante'),
        ),
    ]
