"""`Resolucion.consecutivo_actual` se retira: nadie lo llevaba.

El campo decía «último consecutivo emitido» y nunca se actualizaba: la
numeración la lleva el ERP y llega en el campo `consecutivo` de cada documento,
que se valida contra `rango_desde`/`rango_hasta`. Un contador que siempre marca
cero es peor que no tenerlo, porque invita a fiarse de él.

Se va con él la propiedad `siguiente_consecutivo`, que tampoco llamaba nadie.
"""

# Generated by Django 5.1.15 on 2026-09-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0026_clave_certificado_cifrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolucion',
            name='consecutivo_actual',
        ),
    ]
