# Generated by Django 5.1.15 on 2026-08-27 09:13

import apps.nomina.models.nomina
import apps.utilidades.almacenamiento
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0005_periodonomina_subtipotrabajador_tipocontrato_and_more'),
        ('documentos', '0036_nota_ajuste'),
        ('emisores', '0020_rename_resolucionfacturacion_resolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('numero_documento', models.CharField(help_text='Sin puntos, sin guiones y sin dígito de verificación.', max_length=20, verbose_name='número de documento')),
                ('primer_apellido', models.CharField(max_length=100, verbose_name='primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, verbose_name='segundo apellido')),
                ('primer_nombre', models.CharField(max_length=100, verbose_name='primer nombre')),
                ('otros_nombres', models.CharField(blank=True, max_length=100, verbose_name='otros nombres')),
                ('codigo_trabajador', models.CharField(blank=True, help_text='Código interno del empleador; viaja en el XML.', max_length=20, verbose_name='código del trabajador')),
                ('alto_riesgo_pension', models.BooleanField(default=False, verbose_name='alto riesgo de pensión')),
                ('salario_integral', models.BooleanField(default=False, verbose_name='salario integral')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='sueldo')),
                ('fecha_ingreso', models.DateField(verbose_name='fecha de ingreso')),
                ('fecha_retiro', models.DateField(blank=True, null=True, verbose_name='fecha de retiro')),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección del lugar de trabajo')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='banco')),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], max_length=10, verbose_name='tipo de cuenta')),
                ('numero_cuenta', models.CharField(blank=True, max_length=30, verbose_name='número de cuenta')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='catalogos.departamento', verbose_name='departamento del lugar de trabajo')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='emisores.emisor', verbose_name='emisor')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='catalogos.formapago', verbose_name='forma de pago')),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='catalogos.mediopago', verbose_name='medio de pago')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='catalogos.municipio', verbose_name='municipio del lugar de trabajo')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='catalogos.pais', verbose_name='país del lugar de trabajo')),
                ('subtipo_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='catalogos.subtipotrabajador', verbose_name='subtipo de trabajador')),
                ('tipo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='catalogos.tipocontrato', verbose_name='tipo de contrato')),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='catalogos.tipoidentificacion', verbose_name='tipo de identificación')),
                ('tipo_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='catalogos.tipotrabajador', verbose_name='tipo de trabajador')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'db_table': 'nom_empleado',
                'ordering': ['primer_apellido', 'primer_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefijo', models.CharField(blank=True, help_text='Lo elige el emisor: la nómina no se numera con resolución de la DIAN (regla NIE010).', max_length=10, verbose_name='prefijo')),
                ('consecutivo', models.PositiveBigIntegerField(verbose_name='consecutivo')),
                ('numero', models.CharField(blank=True, help_text='Número del documento. Si se omite, se arma como prefijo + consecutivo.', max_length=30, verbose_name='número')),
                ('fecha_liquidacion_inicio', models.DateField(verbose_name='inicio de la liquidación')),
                ('fecha_liquidacion_fin', models.DateField(verbose_name='fin de la liquidación')),
                ('tiempo_laborado', models.PositiveIntegerField(help_text='Días laborados en el periodo (numeral 8.3.1).', verbose_name='tiempo laborado')),
                ('fecha_generacion', models.DateField(verbose_name='fecha de generación')),
                ('hora_generacion', models.TimeField(verbose_name='hora de generación')),
                ('ambiente', models.PositiveSmallIntegerField(choices=[(1, 'Producción'), (2, 'Habilitación')], default=apps.nomina.models.nomina.ambiente_por_defecto, verbose_name='ambiente DIAN')),
                ('tipo_xml', models.CharField(choices=[('102', 'Documento soporte de pago de nómina electrónica'), ('103', 'Nota de ajuste de documento soporte de pago de nómina')], default='102', max_length=3, verbose_name='tipo de XML')),
                ('cune', models.CharField(blank=True, help_text='Código Único de Nómina Electrónica (SHA-384). Se calcula al firmar.', max_length=96, verbose_name='CUNE')),
                ('novedad', models.BooleanField(default=False, verbose_name='novedad contractual')),
                ('cune_novedad', models.CharField(blank=True, max_length=96, verbose_name='CUNE de la novedad')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('trm', models.DecimalField(blank=True, decimal_places=2, help_text='Solo cuando la moneda no es COP.', max_digits=15, null=True, verbose_name='TRM')),
                ('total_devengados', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='total devengados')),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='total deducciones')),
                ('redondeo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='redondeo')),
                ('total_comprobante', models.DecimalField(decimal_places=2, default=0, help_text='Devengados menos deducciones, más el redondeo.', max_digits=15, verbose_name='total del comprobante')),
                ('xml_archivo', models.FileField(blank=True, storage=apps.utilidades.almacenamiento.almacenamiento_backblaze, upload_to=apps.nomina.models.nomina._ruta_artefacto, verbose_name='XML firmado')),
                ('respuesta_archivo', models.FileField(blank=True, storage=apps.utilidades.almacenamiento.almacenamiento_backblaze, upload_to=apps.nomina.models.nomina._ruta_artefacto, verbose_name='respuesta DIAN (cruda)')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='emisores.emisor', verbose_name='emisor')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='nomina.empleado', verbose_name='empleado')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='documentos.documentoestado', verbose_name='estado')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='catalogos.moneda', verbose_name='moneda')),
                ('periodo_nomina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='catalogos.periodonomina', verbose_name='periodo de nómina')),
            ],
            options={
                'verbose_name': 'nómina electrónica',
                'verbose_name_plural': 'nóminas electrónicas',
                'db_table': 'nom_nomina',
                'ordering': ['-fecha_generacion', '-consecutivo'],
            },
        ),
        migrations.CreateModel(
            name='NominaConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('grupo', models.CharField(choices=[('devengado', 'Devengado'), ('deduccion', 'Deducción')], max_length=10, verbose_name='grupo')),
                ('concepto', models.CharField(choices=[('basico', 'Salario básico'), ('auxilio_transporte', 'Auxilio de transporte'), ('viaticos', 'Viáticos de manutención y alojamiento'), ('hed', 'Hora extra diurna'), ('hen', 'Hora extra nocturna'), ('hrn', 'Hora recargo nocturno'), ('heddf', 'Hora extra diurna dominical o festiva'), ('hrddf', 'Hora recargo diurno dominical o festivo'), ('hendf', 'Hora extra nocturna dominical o festiva'), ('hrndf', 'Hora recargo nocturno dominical o festivo'), ('vacaciones_comunes', 'Vacaciones comunes'), ('vacaciones_compensadas', 'Vacaciones compensadas'), ('prima', 'Prima'), ('cesantias', 'Cesantías'), ('intereses_cesantias', 'Intereses de cesantías'), ('incapacidad', 'Incapacidad'), ('licencia_mp', 'Licencia de maternidad o paternidad'), ('licencia_remunerada', 'Licencia remunerada'), ('licencia_no_remunerada', 'Licencia no remunerada'), ('bonificacion', 'Bonificación'), ('auxilio', 'Auxilio'), ('huelga_legal', 'Huelga legal'), ('otro_concepto', 'Otro concepto'), ('compensacion_ordinaria', 'Compensación ordinaria'), ('compensacion_extraordinaria', 'Compensación extraordinaria'), ('bono_epctv', 'Bono o pago EPCTV'), ('bono_epctv_alimentacion', 'Bono EPCTV de alimentación'), ('comision', 'Comisión'), ('dotacion', 'Dotación'), ('apoyo_sostenimiento', 'Apoyo de sostenimiento'), ('teletrabajo', 'Teletrabajo'), ('bonificacion_retiro', 'Bonificación por retiro'), ('indemnizacion', 'Indemnización'), ('salud', 'Salud'), ('fondo_pension', 'Fondo de pensión'), ('fondo_sp', 'Fondo de solidaridad pensional'), ('fondo_sp_subsistencia', 'Fondo de subsistencia'), ('sindicato', 'Sindicato'), ('sancion_publica', 'Sanción pública'), ('sancion_privada', 'Sanción privada'), ('libranza', 'Libranza'), ('otra_deduccion', 'Otra deducción'), ('pension_voluntaria', 'Pensión voluntaria'), ('retencion_fuente', 'Retención en la fuente'), ('afc', 'AFC'), ('cooperativa', 'Cooperativa'), ('embargo_fiscal', 'Embargo fiscal'), ('plan_complementarios', 'Planes complementarios'), ('educacion', 'Educación'), ('deuda', 'Deuda'), ('pago_tercero', 'Pago a tercero'), ('anticipo', 'Anticipo'), ('reintegro', 'Reintegro')], max_length=30, verbose_name='concepto')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cantidad')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Recargo de la hora extra, o porcentaje de la deducción.', max_digits=6, null=True, verbose_name='porcentaje')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='valor')),
                ('valor_no_salarial', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='valor no salarial')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='fecha de fin')),
                ('hora_inicio', models.DateTimeField(blank=True, null=True, verbose_name='hora de inicio')),
                ('hora_fin', models.DateTimeField(blank=True, null=True, verbose_name='hora de fin')),
                ('descripcion', models.CharField(blank=True, help_text="La piden 'otro concepto' y las libranzas.", max_length=255, verbose_name='descripción')),
                ('tipo_incapacidad', models.CharField(blank=True, choices=[('1', 'Común'), ('2', 'Profesional'), ('3', 'Laboral')], max_length=1, verbose_name='tipo de incapacidad')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='nomina.nomina', verbose_name='nómina')),
            ],
            options={
                'verbose_name': 'concepto de nómina',
                'verbose_name_plural': 'conceptos de nómina',
                'db_table': 'nom_nomina_concepto',
                'ordering': ['grupo', 'concepto', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(fields=('emisor', 'tipo_identificacion', 'numero_documento'), name='empleado_identificacion_unica_por_emisor'),
        ),
        migrations.AddConstraint(
            model_name='nomina',
            constraint=models.UniqueConstraint(fields=('emisor', 'prefijo', 'consecutivo'), name='nomina_numero_unico_por_emisor'),
        ),
    ]
