# Generated by Django 5.1.15 on 2026-09-16 16:23

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('firmado', 'Firmado'), ('enviado', 'Enviado sin veredicto'), ('validado', 'Validado por la DIAN'), ('rechazado', 'Rechazado por la DIAN')], max_length=20, verbose_name='tipo')),
                ('datos', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='datos')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='nomina.nomina', verbose_name='nómina')),
            ],
            options={
                'verbose_name': 'evento de nómina',
                'verbose_name_plural': 'eventos de nómina',
                'db_table': 'nom_nomina_evento',
                'ordering': ['fecha', 'id'],
                'abstract': False,
            },
        ),
    ]
