# Generated by Django 5.1.15 on 2026-08-27 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0020_rename_resolucionfacturacion_resolucion'),
        ('nomina', '0002_nomina_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de validación DIAN'),
        ),
        migrations.CreateModel(
            name='NominaError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('regla', models.CharField(blank=True, max_length=20, verbose_name='regla')),
                ('tipo', models.CharField(choices=[('rechazo', 'Rechazo'), ('notificacion', 'Notificación'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='tipo')),
                ('mensaje', models.TextField(verbose_name='mensaje')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='nomina.nomina', verbose_name='nómina')),
            ],
            options={
                'verbose_name': 'error de nómina',
                'verbose_name_plural': 'errores de nómina',
                'db_table': 'nom_nomina_error',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConsecutivoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('valor', models.PositiveIntegerField(default=0, verbose_name='último consecutivo usado')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consecutivos_archivo_nomina', to='emisores.emisor', verbose_name='emisor')),
            ],
            options={
                'verbose_name': 'consecutivo de archivos',
                'verbose_name_plural': 'consecutivos de archivos',
                'db_table': 'nom_consecutivo_archivo',
                'ordering': ['-anio'],
                'constraints': [models.UniqueConstraint(fields=('emisor', 'anio'), name='consecutivo_archivo_unico_por_anio')],
            },
        ),
    ]
