# Generated by Django 5.1.15 on 2026-08-27 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_envio_dian'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='nomina_predecesora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='nomina.nomina', verbose_name='nómina que ajusta'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='tipo_nota',
            field=models.CharField(blank=True, choices=[('1', 'Reemplazar'), ('2', 'Eliminar')], help_text='Vacío en la nómina; obligatorio en la nota de ajuste.', max_length=1, verbose_name='tipo de nota'),
        ),
    ]
