# Generated by Django 5.1.15 on 2026-08-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0005_condiciones_en_la_nomina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='activo',
        ),
    ]
