# Generated by Django 5.1.15 on 2026-08-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0006_quitar_activo_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_retiro',
        ),
    ]
