# Generated by Django 5.1.15 on 2026-08-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0007_quitar_fecha_retiro_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='envio',
            field=models.CharField(blank=True, choices=[('nomina_sync', 'Síncrono (SendNominaSync)')], help_text='Con qué operación se envió a la DIAN. Vacío mientras no se haya enviado.', max_length=20, verbose_name='operación de envío'),
        ),
    ]
