# Generated by Django 5.1.15 on 2026-08-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0008_nomina_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='ambiente',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Producción'), (2, 'Habilitación')], help_text='Se hereda del ``ambiente_nomina`` del emisor al crear y se sella al firmar: la DIAN habilita la nómina aparte de la facturación, así que un emisor puede estar en producción para una y en habilitación para la otra.', verbose_name='ambiente DIAN'),
        ),
    ]
