# Generated by Django 5.1.15 on 2026-08-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0009_alter_nomina_ambiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='track_id',
            field=models.CharField(blank=True, help_text='Lo devuelve el envío al Set de Pruebas, que es asíncrono: es la llave con la que se consulta esa entrega (GetStatusZip). El envío síncrono no devuelve ninguno; ahí se consulta por el CUNE.', max_length=100, verbose_name='trackId / ZipKey'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='envio',
            field=models.CharField(blank=True, choices=[('test_set', 'Set de Pruebas (SendTestSetAsync)'), ('nomina_sync', 'Síncrono (SendNominaSync)')], help_text='Con qué operación se envió a la DIAN. Vacío mientras no se haya enviado.', max_length=20, verbose_name='operación de envío'),
        ),
    ]
