# Generated by Django 5.1.15 on 2026-09-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_datos_nomina'),
        ('documentos', '0045_indice_listado'),
        ('emisores', '0027_quitar_consecutivo_actual'),
        ('nomina', '0010_nomina_track_id_alter_nomina_envio'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nomina',
            index=models.Index(fields=['emisor', '-fecha_generacion', '-consecutivo'], name='nom_emisor_recientes'),
        ),
    ]
