# Generated by Django 5.1.15 on 2026-06-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('identificacion', models.CharField(blank=True, help_text='NIT o documento del cliente (opcional, sin DV).', max_length=20, verbose_name='identificación')),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, verbose_name='correo de contacto')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'cuenta',
                'verbose_name_plural': 'cuentas',
                'ordering': ['nombre'],
            },
        ),
    ]
