# Generated by Django 5.1.15 on 2026-06-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cuenta',
            table='cue_cuenta',
        ),
    ]
