# Generated by Django 5.1.15 on 2026-10-03 00:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emisores', '0009_webhook_url_http'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=64, verbose_name='alias')),
                ('sha256', models.CharField(max_length=64, unique=True, verbose_name='SHA-256')),
                ('raw_key', models.CharField(max_length=255, verbose_name='clave en R2')),
                ('envelope_from', models.CharField(blank=True, max_length=320, verbose_name='remitente (sobre)')),
                ('envelope_to', models.CharField(max_length=320, verbose_name='destinatario (sobre)')),
                ('message_id', models.CharField(blank=True, max_length=998, verbose_name='Message-ID')),
                ('asunto', models.CharField(blank=True, max_length=998, verbose_name='asunto')),
                ('recibido_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='recibido en')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('sin_documentos', 'Sin documentos'), ('error', 'Error'), ('empresa_desconocida', 'Empresa desconocida'), ('confirmacion_reenvio', 'Confirmación de reenvío')], db_index=True, default='pendiente', max_length=30, verbose_name='estado')),
                ('error_detalle', models.TextField(blank=True, verbose_name='detalle del error')),
                ('intentos', models.PositiveSmallIntegerField(default=0, verbose_name='intentos')),
                ('confirmacion_reenvio', models.TextField(blank=True, verbose_name='confirmación de reenvío')),
                ('emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correos_recibidos', to='emisores.emisor', verbose_name='emisor')),
            ],
            options={
                'verbose_name': 'correo recibido',
                'verbose_name_plural': 'correos recibidos',
                'db_table': 'rec_correo',
                'ordering': ['-recibido_en', '-id'],
            },
        ),
    ]
