# Generated by Django 5.1.15 on 2026-10-03 15:03

import apps.recepcion.models.documento
import apps.utilidades.almacenamiento
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('documentos', '0007_documento_notificacion'),
        ('emisores', '0009_webhook_url_http'),
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(help_text='cbc:ID del documento.', max_length=30, verbose_name='número')),
                ('cufe_cude', models.CharField(help_text='cbc:UUID del documento. CUFE en facturas, CUDE en notas.', max_length=96, unique=True, verbose_name='CUFE/CUDE')),
                ('fecha_emision', models.DateField(verbose_name='fecha de emisión')),
                ('hora_emision', models.TimeField(blank=True, null=True, verbose_name='hora de emisión')),
                ('tipo_codigo_dian', models.CharField(blank=True, help_text='InvoiceTypeCode, CreditNoteTypeCode o DebitNoteTypeCode tal como vino.', max_length=2, verbose_name='código DIAN del tipo')),
                ('proveedor_numero_identificacion', models.CharField(db_index=True, max_length=20, verbose_name='NIT del proveedor')),
                ('proveedor_digito_verificacion', models.CharField(blank=True, max_length=1, verbose_name='DV del proveedor')),
                ('proveedor_razon_social', models.CharField(blank=True, max_length=450, verbose_name='razón social del proveedor')),
                ('receptor_numero_identificacion', models.CharField(max_length=20, verbose_name='NIT del receptor')),
                ('valor_bruto', models.DecimalField(blank=True, decimal_places=2, help_text='cbc:LineExtensionAmount.', max_digits=20, null=True, verbose_name='valor bruto')),
                ('total_impuestos', models.DecimalField(blank=True, decimal_places=2, help_text='Suma de los cbc:TaxAmount de los cac:TaxTotal del documento.', max_digits=20, null=True, verbose_name='total impuestos')),
                ('total_a_pagar', models.DecimalField(blank=True, decimal_places=2, help_text='cbc:PayableAmount.', max_digits=20, null=True, verbose_name='total a pagar')),
                ('validacion_codigo', models.CharField(blank=True, help_text='ValidationResultCode del AttachedDocument (02 = validado).', max_length=10, verbose_name='código de validación DIAN')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de validación DIAN')),
                ('xml_archivo', models.FileField(help_text='El XML tal como llegó: el AttachedDocument o el documento suelto.', storage=apps.utilidades.almacenamiento.almacenamiento_backblaze, upload_to=apps.recepcion.models.documento._ruta_archivo, verbose_name='XML recibido')),
                ('xml_factura_archivo', models.FileField(blank=True, help_text='El documento extraído del AttachedDocument. Vacío si llegó suelto.', storage=apps.utilidades.almacenamiento.almacenamiento_backblaze, upload_to=apps.recepcion.models.documento._ruta_archivo, verbose_name='XML del documento')),
                ('pdf_archivo', models.FileField(blank=True, storage=apps.utilidades.almacenamiento.almacenamiento_backblaze, upload_to=apps.recepcion.models.documento._ruta_archivo, verbose_name='PDF')),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='recepcion.correo', verbose_name='correo')),
                ('documento_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_recibidos', to='documentos.documentotipo', verbose_name='tipo de documento')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_recibidos', to='emisores.emisor', verbose_name='emisor')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_recibidos', to='catalogos.moneda', verbose_name='moneda')),
            ],
            options={
                'verbose_name': 'documento recibido',
                'verbose_name_plural': 'documentos recibidos',
                'db_table': 'rec_documento',
                'ordering': ['-fecha_emision', '-creado_en'],
                'indexes': [models.Index(fields=['emisor', '-fecha_emision'], name='rec_doc_emisor_recientes')],
            },
        ),
    ]
