# Generated by Django 5.1.15 on 2026-10-03 16:57

import apps.recepcion.models.adjunto
import apps.utilidades.almacenamiento
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('documentos', '0007_documento_notificacion'),
        ('emisores', '0009_webhook_url_http'),
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(help_text='cbc:ID del documento.', max_length=30, verbose_name='número')),
                ('cufe_cude', models.CharField(help_text='cbc:UUID del documento. CUFE en facturas, CUDE en notas.', max_length=96, unique=True, verbose_name='CUFE/CUDE')),
                ('fecha_emision', models.DateField(verbose_name='fecha de emisión')),
                ('hora_emision', models.TimeField(blank=True, null=True, verbose_name='hora de emisión')),
                ('tipo_codigo_dian', models.CharField(blank=True, help_text='InvoiceTypeCode, CreditNoteTypeCode o DebitNoteTypeCode tal como vino.', max_length=2, verbose_name='código DIAN del tipo')),
                ('proveedor_numero_identificacion', models.CharField(db_index=True, max_length=20, verbose_name='NIT del proveedor')),
                ('proveedor_digito_verificacion', models.CharField(blank=True, max_length=1, verbose_name='DV del proveedor')),
                ('proveedor_razon_social', models.CharField(blank=True, max_length=450, verbose_name='razón social del proveedor')),
                ('receptor_numero_identificacion', models.CharField(max_length=20, verbose_name='NIT del receptor')),
                ('valor_bruto', models.DecimalField(blank=True, decimal_places=2, help_text='cbc:LineExtensionAmount.', max_digits=20, null=True, verbose_name='valor bruto')),
                ('total_impuestos', models.DecimalField(blank=True, decimal_places=2, help_text='Suma de los cbc:TaxAmount de los cac:TaxTotal del documento.', max_digits=20, null=True, verbose_name='total impuestos')),
                ('total_a_pagar', models.DecimalField(blank=True, decimal_places=2, help_text='cbc:PayableAmount.', max_digits=20, null=True, verbose_name='total a pagar')),
                ('validacion_codigo', models.CharField(blank=True, help_text='ValidationResultCode del AttachedDocument (02 = validado).', max_length=10, verbose_name='código de validación DIAN')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de validación DIAN')),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='recepcion.correo', verbose_name='correo')),
                ('documento_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_recibidos', to='documentos.documentotipo', verbose_name='tipo de documento')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_recibidos', to='emisores.emisor', verbose_name='emisor')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_recibidos', to='catalogos.moneda', verbose_name='moneda')),
            ],
            options={
                'verbose_name': 'documento recibido',
                'verbose_name_plural': 'documentos recibidos',
                'db_table': 'rec_documento',
                'ordering': ['-fecha_emision', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('xml', 'XML recibido'), ('xml_documento', 'XML del documento'), ('pdf', 'PDF del documento'), ('otro', 'Otro adjunto')], max_length=20, verbose_name='rol')),
                ('archivo', models.FileField(max_length=300, storage=apps.utilidades.almacenamiento.almacenamiento_backblaze, upload_to=apps.recepcion.models.adjunto._ruta, verbose_name='archivo')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre original')),
                ('tipo_contenido', models.CharField(max_length=100, verbose_name='tipo de contenido')),
                ('tamano', models.PositiveBigIntegerField(verbose_name='tamaño en bytes')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='recepcion.correo', verbose_name='correo')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='recepcion.documento', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'adjunto',
                'verbose_name_plural': 'adjuntos',
                'db_table': 'rec_adjunto',
                'ordering': ['creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['emisor', '-fecha_emision'], name='rec_doc_emisor_recientes'),
        ),
        migrations.AddConstraint(
            model_name='adjunto',
            constraint=models.UniqueConstraint(condition=models.Q(('documento__isnull', False)), fields=('documento', 'rol'), name='rec_adjunto_rol_unico_por_documento'),
        ),
        migrations.AddConstraint(
            model_name='adjunto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('documento__isnull', True), ('rol', 'otro')), models.Q(('documento__isnull', False), models.Q(('rol', 'otro'), _negated=True)), _connector='OR'), name='rec_adjunto_rol_coherente'),
        ),
    ]
