# Generated by Django 5.1.15 on 2026-10-08 14:33

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_eventos_radian_y_festivos'),
        ('documentos', '0007_documento_notificacion'),
        ('emisores', '0011_software_modulo'),
        ('recepcion', '0002_documento_adjunto'),
    ]

    operations = [
        # Los índices GIN de trigramas la necesitan. `pg_trgm` es una extensión
        # "trusted" desde PostgreSQL 13: la crea el dueño de la base sin ser
        # superusuario. Si ya existe, no hace nada.
        TrigramExtension(),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-fecha_emision', '-creado_en', '-id'], 'verbose_name': 'documento recibido', 'verbose_name_plural': 'documentos recibidos'},
        ),
        migrations.RemoveIndex(
            model_name='documento',
            name='rec_doc_emisor_recientes',
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['emisor', '-fecha_emision', '-creado_en', '-id'], name='rec_doc_emisor_recientes'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(django.db.models.functions.text.Upper('cufe_cude'), name='rec_doc_cufe_upper'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('proveedor_numero_identificacion'), name='gin_trgm_ops'), name='rec_doc_nit_trgm'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('numero'), name='gin_trgm_ops'), name='rec_doc_numero_trgm'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('proveedor_razon_social'), name='gin_trgm_ops'), name='rec_doc_razon_social_trgm'),
        ),
    ]
