# Generated by Django 5.1.15 on 2026-10-08 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0011_software_modulo'),
        ('recepcion', '0003_documento_paginacion_busqueda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='emisor',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_recibidos', to='emisores.emisor', verbose_name='emisor'),
        ),
    ]
