# Generated by Django 5.1.15 on 2026-10-08 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0004_documento_emisor_sin_indice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='correo',
            name='origen',
            field=models.CharField(choices=[('correo', 'Correo'), ('carga', 'Carga manual')], default='correo', max_length=10, verbose_name='origen'),
        ),
        migrations.AddField(
            model_name='correo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_recepcion', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='correo',
            name='sha256',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='SHA-256'),
        ),
    ]
