# Generated by Django 5.1.15 on 2026-10-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0005_correo_origen_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='ambiente',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Producción'), (2, 'Habilitación')], help_text='ProfileExecutionID del XML. Vacío si no venía: se verifica en producción.', null=True, verbose_name='ambiente'),
        ),
        migrations.AddField(
            model_name='documento',
            name='verificacion_codigo',
            field=models.CharField(blank=True, help_text='StatusCode que respondió la DIAN.', max_length=10, verbose_name='código de la verificación'),
        ),
        migrations.AddField(
            model_name='documento',
            name='verificacion_descripcion',
            field=models.TextField(blank=True, help_text='StatusDescription y errores de la DIAN, o por qué no se pudo consultar.', verbose_name='detalle de la verificación'),
        ),
        migrations.AddField(
            model_name='documento',
            name='verificacion_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('valido', 'Válido'), ('invalido', 'No válido'), ('no_verificable', 'No verificable'), ('error', 'Error al consultar')], default='pendiente', max_length=20, verbose_name='verificación DIAN'),
        ),
        migrations.AddField(
            model_name='documento',
            name='verificado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verificado en'),
        ),
    ]
