# Generated by Django 5.1.15 on 2026-10-10 00:33

import apps.recepcion.models.evento
import apps.utilidades.almacenamiento
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_eventos_radian_y_festivos'),
        ('emisores', '0012_eventos_radian'),
        ('recepcion', '0006_documento_verificacion_dian'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='proveedor_tipo_identificacion',
            field=models.CharField(blank=True, help_text='schemeName del CompanyID (31 = NIT, 13 = cédula).', max_length=2, verbose_name='tipo de identificación del proveedor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='proveedor_tipo_organizacion',
            field=models.CharField(blank=True, help_text='AdditionalAccountID (1 = jurídica, 2 = natural).', max_length=1, verbose_name='tipo de organización del proveedor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='radian_estado',
            field=models.CharField(choices=[('sin_eventos', 'Sin eventos'), ('acuse', 'Acuse de recibo (030)'), ('recibo', 'Recibo del bien o servicio (032)'), ('aceptada', 'Aceptación expresa (033)'), ('reclamada', 'Reclamo (031)')], default='sin_eventos', help_text='El último evento registrado en RADIAN. El detalle está en rec_evento.', max_length=20, verbose_name='estado RADIAN'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(help_text='cbc:ID del evento.', max_length=30, verbose_name='número')),
                ('consecutivo', models.PositiveIntegerField(verbose_name='consecutivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('registrado', 'Registrado'), ('rechazado', 'Rechazado'), ('error', 'Error al enviar')], db_index=True, default='pendiente', max_length=20, verbose_name='estado')),
                ('ambiente', models.PositiveSmallIntegerField(choices=[(1, 'Producción'), (2, 'Habilitación')], verbose_name='ambiente')),
                ('cude', models.CharField(blank=True, max_length=96, verbose_name='CUDE')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('persona_numero_identificacion', models.CharField(blank=True, max_length=20, verbose_name='identificación de quien recibe')),
                ('persona_nombres', models.CharField(blank=True, max_length=100, verbose_name='nombres de quien recibe')),
                ('persona_apellidos', models.CharField(blank=True, max_length=100, verbose_name='apellidos de quien recibe')),
                ('persona_cargo', models.CharField(blank=True, max_length=100, verbose_name='cargo de quien recibe')),
                ('persona_area', models.CharField(blank=True, max_length=100, verbose_name='área de quien recibe')),
                ('respuesta_codigo', models.CharField(blank=True, max_length=10, verbose_name='código de la respuesta')),
                ('respuesta_descripcion', models.TextField(blank=True, verbose_name='detalle de la respuesta')),
                ('enviado_en', models.DateTimeField(blank=True, null=True, verbose_name='enviado en')),
                ('intentos', models.PositiveSmallIntegerField(default=0, verbose_name='intentos de envío')),
                ('xml_archivo', models.FileField(blank=True, storage=apps.utilidades.almacenamiento.almacenamiento_backblaze, upload_to=apps.recepcion.models.evento._ruta, verbose_name='XML firmado')),
                ('respuesta_archivo', models.FileField(blank=True, storage=apps.utilidades.almacenamiento.almacenamiento_backblaze, upload_to=apps.recepcion.models.evento._ruta, verbose_name='ApplicationResponse de la DIAN')),
                ('concepto_reclamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='catalogos.conceptoreclamo', verbose_name='concepto del reclamo')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='recepcion.documento', verbose_name='documento')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_recepcion', to='emisores.emisor', verbose_name='emisor')),
                ('evento_radian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='catalogos.eventoradian', verbose_name='evento')),
                ('persona_tipo_identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.tipoidentificacion', verbose_name='tipo de identificación de quien recibe')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_recepcion', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'evento RADIAN',
                'verbose_name_plural': 'eventos RADIAN',
                'db_table': 'rec_evento',
                'ordering': ['-creado_en', '-id'],
                'indexes': [models.Index(fields=['documento', 'evento_radian'], name='rec_evento_documento')],
                'constraints': [models.UniqueConstraint(fields=('emisor', 'evento_radian', 'consecutivo'), name='rec_evento_consecutivo_unico')],
            },
        ),
    ]
