# Generated by Django 5.1.15 on 2026-10-10 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_eventos_radian_y_festivos'),
        ('recepcion', '0007_eventos_radian'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='forma_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_recibidos', to='catalogos.formapago', verbose_name='forma de pago'),
        ),
    ]
