# Generated by Django 5.1.15 on 2026-10-10 02:46

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Max


def desde_los_eventos(apps, schema_editor):
    """El contador arranca en el número más alto que ya se dio, por emisor y tipo."""
    Evento = apps.get_model("recepcion", "Evento")
    ConsecutivoEvento = apps.get_model("recepcion", "ConsecutivoEvento")
    filas = Evento.objects.order_by().values("emisor", "evento_radian").annotate(
        ultimo=Max("consecutivo"),
    )
    for fila in filas:
        ConsecutivoEvento.objects.create(
            emisor_id=fila["emisor"], evento_radian_id=fila["evento_radian"],
            ultimo=fila["ultimo"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_eventos_radian_y_festivos'),
        ('emisores', '0012_eventos_radian'),
        ('recepcion', '0008_documento_forma_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo', models.PositiveIntegerField(default=0, verbose_name='último consecutivo')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consecutivos_evento', to='emisores.emisor', verbose_name='emisor')),
                ('evento_radian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.eventoradian', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'consecutivo de evento RADIAN',
                'verbose_name_plural': 'consecutivos de eventos RADIAN',
                'db_table': 'rec_consecutivo_evento',
                'constraints': [models.UniqueConstraint(fields=('emisor', 'evento_radian'), name='rec_consecutivo_evento_unico')],
            },
        ),
        migrations.RunPython(desde_los_eventos, migrations.RunPython.noop),
    ]
