# Generated by Django 5.1.15 on 2026-06-21 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('emisores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adquirente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('razon_social', models.CharField(max_length=450, verbose_name='razón social')),
                ('numero_identificacion', models.CharField(help_text='Sin puntos, sin guiones y sin dígito de verificación.', max_length=20, verbose_name='número de identificación')),
                ('digito_verificacion', models.CharField(blank=True, max_length=1, verbose_name='dígito de verificación')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adquirentes', to='catalogos.departamento', verbose_name='departamento')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adquirentes', to='catalogos.municipio', verbose_name='municipio')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adquirentes', to='catalogos.pais', verbose_name='país')),
                ('responsabilidades', models.ManyToManyField(blank=True, related_name='adquirentes', to='catalogos.responsabilidadfiscal', verbose_name='responsabilidades fiscales')),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adquirentes', to='catalogos.tipoidentificacion', verbose_name='tipo de identificación')),
                ('tipo_organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adquirentes', to='catalogos.tipoorganizacion', verbose_name='tipo de organización')),
            ],
            options={
                'verbose_name': 'adquirente',
                'verbose_name_plural': 'adquirentes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoElectronico',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('factura_venta', 'Factura de venta'), ('nota_credito', 'Nota crédito'), ('nota_debito', 'Nota débito'), ('documento_soporte', 'Documento soporte'), ('nomina', 'Nómina electrónica')], max_length=20, verbose_name='tipo')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generado', 'XML generado'), ('firmado', 'Firmado'), ('enviado', 'Enviado a la DIAN'), ('aceptado', 'Aceptado por la DIAN'), ('rechazado', 'Rechazado por la DIAN')], default='borrador', max_length=20, verbose_name='estado')),
                ('prefijo', models.CharField(blank=True, max_length=10, verbose_name='prefijo')),
                ('consecutivo', models.PositiveBigIntegerField(verbose_name='consecutivo')),
                ('numero', models.CharField(help_text='Prefijo concatenado con el consecutivo (cbc:ID).', max_length=30, verbose_name='número')),
                ('cufe_cude', models.CharField(blank=True, help_text='Hash SHA-384 (96 hex). CUFE en facturas, CUDE en notas/soporte.', max_length=96, verbose_name='CUFE/CUDE')),
                ('fecha_emision', models.DateField(verbose_name='fecha de emisión')),
                ('hora_emision', models.TimeField(verbose_name='hora de emisión')),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, help_text='LineExtensionAmount: suma de las líneas.', max_digits=18, verbose_name='valor bruto (sin impuestos)')),
                ('total_impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='total impuestos')),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='total descuentos')),
                ('total_cargos', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='total cargos')),
                ('total_a_pagar', models.DecimalField(decimal_places=2, default=0, help_text='PayableAmount.', max_digits=18, verbose_name='total a pagar')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('xml_firmado', models.TextField(blank=True, verbose_name='XML firmado')),
                ('respuesta_dian', models.TextField(blank=True, verbose_name='respuesta DIAN')),
                ('adquirente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.adquirente', verbose_name='adquirente')),
                ('documento_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='documentos.documentoelectronico', verbose_name='documento de referencia')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='emisores.emisor', verbose_name='emisor')),
                ('forma_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='catalogos.formapago', verbose_name='forma de pago')),
                ('medio_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='catalogos.mediopago', verbose_name='medio de pago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='catalogos.moneda', verbose_name='moneda')),
                ('resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='emisores.resolucionfacturacion', verbose_name='resolución')),
            ],
            options={
                'verbose_name': 'documento electrónico',
                'verbose_name_plural': 'documentos electrónicos',
                'ordering': ['-fecha_emision', '-consecutivo'],
            },
        ),
        migrations.CreateModel(
            name='LineaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('numero_linea', models.PositiveIntegerField(verbose_name='número de línea')),
                ('descripcion', models.CharField(max_length=500, verbose_name='descripción')),
                ('codigo_producto', models.CharField(blank=True, max_length=100, verbose_name='código del producto')),
                ('cantidad', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='valor unitario')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, help_text='cantidad × valor unitario (LineExtensionAmount).', max_digits=18, verbose_name='valor total de la línea')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='descuento')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='documentos.documentoelectronico', verbose_name='documento')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='catalogos.unidadmedida', verbose_name='unidad de medida')),
            ],
            options={
                'verbose_name': 'línea de documento',
                'verbose_name_plural': 'líneas de documento',
                'ordering': ['numero_linea'],
            },
        ),
        migrations.CreateModel(
            name='ImpuestoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('base_gravable', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='base gravable')),
                ('tarifa', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='tarifa (%)')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='valor del impuesto')),
                ('tributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impuestos_linea', to='catalogos.tributo', verbose_name='tributo')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='documentos.lineadocumento', verbose_name='línea')),
            ],
            options={
                'verbose_name': 'impuesto de línea',
                'verbose_name_plural': 'impuestos de línea',
            },
        ),
        migrations.AddConstraint(
            model_name='documentoelectronico',
            constraint=models.UniqueConstraint(fields=('emisor', 'prefijo', 'consecutivo', 'tipo'), name='documento_numero_unico_por_emisor'),
        ),
        migrations.AddConstraint(
            model_name='lineadocumento',
            constraint=models.UniqueConstraint(fields=('documento', 'numero_linea'), name='linea_numero_unico_por_documento'),
        ),
    ]
