# Generated by Django 5.1.15 on 2026-09-08 19:58

import apps.documentos.models.documento
import apps.utilidades.almacenamiento
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivoArchivoDocumentoEquivalente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('valor', models.PositiveIntegerField(default=0, verbose_name='último consecutivo usado')),
            ],
            options={
                'verbose_name': 'consecutivo de archivos de documento equivalente',
                'verbose_name_plural': 'consecutivos de archivos de documento equivalente',
                'db_table': 'doc_consecutivo_archivo_de',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefijo', models.CharField(blank=True, max_length=10, verbose_name='prefijo')),
                ('consecutivo', models.PositiveBigIntegerField(verbose_name='consecutivo')),
                ('numero', models.CharField(blank=True, help_text='Número del documento (cbc:ID). Si se omite, se arma como prefijo + consecutivo.', max_length=30, verbose_name='número')),
                ('ambiente', models.PositiveSmallIntegerField(choices=[(1, 'Producción'), (2, 'Habilitación')], help_text='ProfileExecutionID del XML: 1 producción, 2 habilitación. Se hereda del emisor al crear y se sella al firmar; no lo decide el ajuste del servidor.', verbose_name='ambiente DIAN')),
                ('cufe_cude', models.CharField(blank=True, help_text='Hash SHA-384 (96 hex). CUFE en facturas, CUDE en notas/soporte.', max_length=96, verbose_name='CUFE/CUDE')),
                ('fecha_emision', models.DateField(default=apps.documentos.models.documento.fecha_por_defecto, help_text='IssueDate del XML. Si se omite se toma la fecha de hoy, que es la única con la que se puede firmar (regla FAD09).', verbose_name='fecha de emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='DueDate del XML: hasta cuándo hay plazo para pagar. La DIAN la exige cuando la forma de pago es a crédito; en contado sobra.', null=True, verbose_name='fecha de vencimiento')),
                ('hora_emision', models.TimeField(default=apps.documentos.models.documento.hora_por_defecto, help_text='IssueTime del XML. Si se omite se toma la hora actual, y al firmar se reescribe con la hora de la firma.', verbose_name='hora de emisión')),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, help_text='LineExtensionAmount: suma de las líneas.', max_digits=18, verbose_name='valor bruto (sin impuestos)')),
                ('total_impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='total impuestos')),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, help_text='Descuentos globales del documento (no los de línea).', max_digits=18, verbose_name='total descuentos')),
                ('descuentos_motivo', models.CharField(blank=True, help_text='cbc:AllowanceChargeReason del descuento global.', max_length=255, verbose_name='motivo de los descuentos')),
                ('total_cargos', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='total cargos')),
                ('cargos_motivo', models.CharField(blank=True, help_text='cbc:AllowanceChargeReason del cargo global.', max_length=255, verbose_name='motivo de los cargos')),
                ('total_a_pagar', models.DecimalField(decimal_places=2, default=0, help_text='PayableAmount.', max_digits=18, verbose_name='total a pagar')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('track_id', models.CharField(blank=True, help_text='Identificador del envío (ZipKey del Set de Pruebas o trackId), para consultar el estado en la DIAN.', max_length=100, verbose_name='track id DIAN')),
                ('envio', models.CharField(blank=True, choices=[('test_set', 'Set de Pruebas (SendTestSetAsync)'), ('bill_sync', 'Síncrono (SendBillSync)')], help_text='Con qué operación se envió a la DIAN. Decide cómo se consulta después el estado: GetStatusZip para el Set de Pruebas (el track_id es un ZipKey) y GetStatus para el envío síncrono. Vacío mientras no se haya enviado.', max_length=20, verbose_name='operación de envío')),
                ('notificado', models.BooleanField(default=False, help_text='Si ya se le entregó el documento al comprador. Lo marca la acción `notificar`; mientras el envío por correo no exista, significa que el paquete se armó y se entregó a quien lo pidió.', verbose_name='notificado al adquiriente')),
                ('fecha_validacion', models.DateTimeField(blank=True, help_text='Momento en que la DIAN aceptó el documento.', null=True, verbose_name='fecha y hora de validación DIAN')),
                ('xml_archivo', models.FileField(blank=True, storage=apps.utilidades.almacenamiento.almacenamiento_backblaze, upload_to=apps.documentos.models.documento._ruta_artefacto, verbose_name='XML firmado')),
                ('respuesta_archivo', models.FileField(blank=True, storage=apps.utilidades.almacenamiento.almacenamiento_backblaze, upload_to=apps.documentos.models.documento._ruta_artefacto, verbose_name='respuesta DIAN (cruda)')),
                ('orden_compra', models.CharField(blank=True, help_text='Número de la orden de compra del adquiriente, si la hubo.', max_length=100, verbose_name='orden de compra')),
                ('orden_compra_fecha', models.DateField(blank=True, null=True, verbose_name='fecha de la orden de compra')),
                ('orden_compra_tipo', models.CharField(blank=True, help_text='cbc:OrderTypeCode: qué clase de orden es (contrato, pedido…), según la codificación que use el comprador.', max_length=20, verbose_name='tipo de la orden de compra')),
                ('orden_compra_documento', models.CharField(blank=True, help_text='cac:DocumentReference/cbc:ID: el soporte de la orden (contrato, acuerdo marco) cuando es distinto del número de la orden.', max_length=100, verbose_name='documento de la orden de compra')),
                ('concepto_correccion', models.CharField(blank=True, help_text='ResponseCode del DiscrepancyResponse: por qué se corrige el documento referenciado. Los códigos válidos dependen del tipo de nota (ConceptoNotaCredito, ConceptoNotaDebito, ConceptoNotaAjuste). Vacío en lo que no es nota.', max_length=2, verbose_name='concepto de corrección')),
            ],
            options={
                'verbose_name': 'documento electrónico',
                'verbose_name_plural': 'documentos electrónicos',
                'db_table': 'doc_documento',
                'ordering': ['-fecha_emision', '-consecutivo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('numero_linea', models.PositiveIntegerField(verbose_name='número de línea')),
                ('descripcion', models.CharField(max_length=500, verbose_name='descripción')),
                ('codigo_producto', models.CharField(blank=True, max_length=100, verbose_name='código del producto')),
                ('cantidad', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='valor unitario')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, help_text='cantidad × valor unitario (LineExtensionAmount).', max_digits=18, verbose_name='valor total del detalle')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Descuento ya aplicado en el valor total de la línea: el cac:AllowanceCharge lo declara con BaseAmount = valor_total + descuento.', max_digits=18, verbose_name='descuento')),
                ('descuento_motivo', models.CharField(blank=True, help_text='cbc:AllowanceChargeReason de la línea.', max_length=255, verbose_name='motivo del descuento')),
                ('nota', models.CharField(blank=True, help_text='cbc:Note de la línea: aclaración libre sobre este ítem.', max_length=500, verbose_name='nota de la línea')),
                ('marca', models.CharField(blank=True, help_text='cbc:BrandName del ítem.', max_length=100, verbose_name='marca')),
                ('modelo', models.CharField(blank=True, help_text='cbc:ModelName del ítem.', max_length=100, verbose_name='modelo')),
                ('centro_costo', models.CharField(blank=True, help_text='cbc:AccountingCostCode: a qué centro de costo se imputa.', max_length=50, verbose_name='centro de costo')),
                ('periodo_desde', models.DateField(blank=True, help_text='cac:InvoicePeriod/cbc:StartDate: para servicios por periodo.', null=True, verbose_name='periodo facturado desde')),
                ('periodo_hasta', models.DateField(blank=True, help_text='cac:InvoicePeriod/cbc:EndDate.', null=True, verbose_name='periodo facturado hasta')),
                ('periodo_descripcion', models.CharField(blank=True, help_text="cac:InvoicePeriod/cbc:Description: el periodo en palabras (p. ej. 'Agosto de 2026').", max_length=255, verbose_name='descripción del periodo')),
                ('periodo_descripcion_codigo', models.CharField(blank=True, help_text='cac:InvoicePeriod/cbc:DescriptionCode.', max_length=20, verbose_name='código de la descripción del periodo')),
            ],
            options={
                'verbose_name': 'detalle de documento',
                'verbose_name_plural': 'detalles de documento',
                'db_table': 'doc_documento_detalle',
                'ordering': ['numero_linea'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalleImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('base_gravable', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='base gravable')),
                ('tarifa', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='tarifa (%)')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='valor del impuesto')),
            ],
            options={
                'verbose_name': 'impuesto de detalle',
                'verbose_name_plural': 'impuestos de detalle',
                'db_table': 'doc_documento_detalle_impuesto',
            },
        ),
        migrations.CreateModel(
            name='DocumentoError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('regla', models.CharField(blank=True, max_length=20, verbose_name='regla')),
                ('tipo', models.CharField(choices=[('rechazo', 'Rechazo'), ('notificacion', 'Notificación'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='tipo')),
                ('mensaje', models.TextField(verbose_name='mensaje')),
            ],
            options={
                'verbose_name': 'error de documento',
                'verbose_name_plural': 'errores de documento',
                'db_table': 'doc_documento_error',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(blank=True, help_text='Código de la DIAN para el estado (opcional).', max_length=10, verbose_name='código DIAN')),
                ('nombre', models.CharField(choices=[('borrador', 'Borrador'), ('generado', 'XML generado'), ('firmado', 'Firmado'), ('enviado', 'Enviado a la DIAN'), ('aceptado', 'Aceptado por la DIAN'), ('rechazado', 'Rechazado por la DIAN')], max_length=20, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'estado de documento',
                'verbose_name_plural': 'estados de documento',
                'db_table': 'doc_documento_estado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('caja_placa', models.CharField(help_text='Placa de inventario de la caja (par `PlacaCaja`).', max_length=50, verbose_name='placa de la caja')),
                ('caja_ubicacion', models.CharField(help_text='Dónde estaba la caja (par `UbicaciónCaja`, con tilde: es el literal que compara la DIAN).', max_length=255, verbose_name='ubicación de la caja')),
                ('caja_tipo', models.CharField(help_text="Par `TipoCaja`. El anexo no da lista de valores; la ejemplificación oficial usa texto libre ('Caja de apoyo').", max_length=100, verbose_name='tipo de caja')),
                ('cajero', models.CharField(help_text='Nombres y apellidos del cajero o vendedor (par `Cajero`).', max_length=200, verbose_name='cajero')),
                ('codigo_venta', models.CharField(help_text='Identificador interno de la transacción (par `CódigoVenta`, con tilde).', max_length=50, verbose_name='código de la venta')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Par `SubTotal`. Si se deja vacío se emite el `valor_bruto` del documento. Se admite informarlo aparte porque la ejemplificación oficial trae ahí un importe distinto del LineExtensionAmount y el anexo no aclara la diferencia.', max_digits=15, null=True, verbose_name='subtotal de la venta')),
                ('comprador_codigo', models.CharField(blank=True, help_text='Documento de identidad del comprador. Vacío emite el del adquiriente del documento.', max_length=50, verbose_name='código del comprador')),
                ('comprador_nombres', models.CharField(blank=True, help_text='Vacío emite el nombre del adquiriente del documento.', max_length=200, verbose_name='nombres del comprador')),
                ('comprador_puntos', models.PositiveIntegerField(default=0, help_text='Puntos del programa de fidelización. Cero si no hay programa: el par es obligatorio y omitirlo es un rechazo.', verbose_name='puntos acumulados')),
            ],
            options={
                'verbose_name': 'datos P.O.S. del documento',
                'verbose_name_plural': 'datos P.O.S. de los documentos',
                'db_table': 'doc_documento_pos',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(choices=[('factura_venta', 'Factura de venta'), ('nota_credito', 'Nota crédito'), ('nota_debito', 'Nota débito'), ('documento_soporte', 'Documento soporte'), ('nota_ajuste', 'Nota de ajuste al documento soporte'), ('nomina', 'Nómina electrónica'), ('documento_equivalente_pos', 'Documento equivalente P.O.S.'), ('nota_ajuste_de_credito', 'Nota de ajuste crédito al documento equivalente'), ('nota_ajuste_de_debito', 'Nota de ajuste débito al documento equivalente')], help_text='Discriminador interno que define la lógica de generación.', max_length=30, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('codigo_dian', models.CharField(blank=True, help_text='InvoiceTypeCode oficial (01, 02, 91, 92, 05, 20).', max_length=2, verbose_name='código DIAN (InvoiceTypeCode)')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documento',
                'db_table': 'doc_documento_tipo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Adquiriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('razon_social', models.CharField(max_length=450, verbose_name='razón social')),
                ('primer_nombre', models.CharField(blank=True, max_length=100, verbose_name='primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, verbose_name='segundo nombre')),
                ('primer_apellido', models.CharField(blank=True, max_length=100, verbose_name='primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, verbose_name='segundo apellido')),
                ('numero_identificacion', models.CharField(help_text='Sin puntos, sin guiones y sin dígito de verificación.', max_length=20, verbose_name='número de identificación')),
                ('digito_verificacion', models.CharField(blank=True, max_length=1, verbose_name='dígito de verificación')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('codigo_postal', models.CharField(blank=True, help_text='cbc:PostalZone de las direcciones del XML.', max_length=10, verbose_name='código postal')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adquirientes', to='catalogos.departamento', verbose_name='departamento')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adquirientes', to='catalogos.municipio', verbose_name='municipio')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adquirientes', to='catalogos.pais', verbose_name='país')),
                ('responsabilidades', models.ManyToManyField(blank=True, related_name='adquirientes', to='catalogos.responsabilidadfiscal', verbose_name='responsabilidades fiscales')),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adquirientes', to='catalogos.tipoidentificacion', verbose_name='tipo de identificación')),
                ('tipo_organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adquirientes', to='catalogos.tipoorganizacion', verbose_name='tipo de organización')),
            ],
            options={
                'verbose_name': 'adquiriente',
                'verbose_name_plural': 'adquirientes',
                'db_table': 'doc_adquiriente',
                'ordering': ['razon_social'],
            },
        ),
    ]
