# Generated by Django 5.1.15 on 2026-09-08 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('documentos', '0001_initial'),
        ('emisores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consecutivoarchivodocumentoequivalente',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consecutivos_archivo_documento_equivalente', to='emisores.emisor', verbose_name='emisor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='documento_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='documentos.documento', verbose_name='documento de referencia'),
        ),
        migrations.AddField(
            model_name='documento',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='emisores.emisor', verbose_name='emisor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='forma_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='catalogos.formapago', verbose_name='forma de pago'),
        ),
        migrations.AddField(
            model_name='documento',
            name='medio_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='catalogos.mediopago', verbose_name='medio de pago'),
        ),
        migrations.AddField(
            model_name='documento',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='catalogos.moneda', verbose_name='moneda'),
        ),
        migrations.AddField(
            model_name='documento',
            name='resolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='emisores.resolucion', verbose_name='resolución'),
        ),
        migrations.AddField(
            model_name='adquiriente',
            name='documento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adquiriente', to='documentos.documento', verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='documentodetalle',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='documentos.documento', verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='documentodetalle',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='catalogos.unidadmedida', verbose_name='unidad de medida'),
        ),
        migrations.AddField(
            model_name='documentodetalleimpuesto',
            name='detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='documentos.documentodetalle', verbose_name='detalle'),
        ),
        migrations.AddField(
            model_name='documentodetalleimpuesto',
            name='tributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impuestos_detalle', to='catalogos.tributo', verbose_name='tributo'),
        ),
        migrations.AddField(
            model_name='documentoerror',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='documentos.documento', verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.documentoestado', verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='documentopos',
            name='documento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='documentos.documento', verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='documento_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.documentotipo', verbose_name='tipo de documento'),
        ),
        migrations.AddConstraint(
            model_name='consecutivoarchivodocumentoequivalente',
            constraint=models.UniqueConstraint(fields=('emisor', 'anio'), name='consecutivo_archivo_de_unico_por_anio'),
        ),
        migrations.AddConstraint(
            model_name='documentodetalle',
            constraint=models.UniqueConstraint(fields=('documento', 'numero_linea'), name='documento_detalle_numero_unico'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['emisor', '-fecha_emision', '-consecutivo'], name='doc_emisor_recientes'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(fields=('emisor', 'prefijo', 'consecutivo', 'documento_tipo'), name='documento_numero_unico_por_emisor'),
        ),
    ]
