# Generated by Django 5.1.15 on 2026-06-24 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('seguridad', '0003_usuario_cuenta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoelectronico',
            name='origen_llave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='seguridad.llaveapi', verbose_name='origen (llave de API)'),
        ),
        migrations.AddField(
            model_name='documentoelectronico',
            name='origen_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='origen (usuario)'),
        ),
    ]
