# Generated by Django 5.1.15 on 2026-06-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documentoelectronico_origen_llave_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adquirente',
            table='doc_adquirente',
        ),
        migrations.AlterModelTable(
            name='documentoelectronico',
            table='doc_documentoelectronico',
        ),
        migrations.AlterModelTable(
            name='impuestolinea',
            table='doc_impuestolinea',
        ),
        migrations.AlterModelTable(
            name='lineadocumento',
            table='doc_lineadocumento',
        ),
    ]
