# Generated by Django 5.1.15 on 2026-06-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_alter_adquirente_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='documentoelectronico',
            table='doc_documento_electronico',
        ),
        migrations.AlterModelTable(
            name='impuestolinea',
            table='doc_impuesto_linea',
        ),
        migrations.AlterModelTable(
            name='lineadocumento',
            table='doc_linea_documento',
        ),
    ]
