# Generated by Django 5.1.15 on 2026-09-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='respuesta_validado',
            field=models.BooleanField(default=False, verbose_name='respuesta de validado'),
        ),
    ]
