# Generated by Django 5.1.15 on 2026-06-29 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_alter_conceptonotacredito_table_and_more'),
        ('documentos', '0005_rename_adquirente_adquiriente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adquiriente',
            options={'ordering': ['razon_social'], 'verbose_name': 'adquiriente', 'verbose_name_plural': 'adquirientes'},
        ),
        migrations.AlterField(
            model_name='adquiriente',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adquirientes', to='catalogos.departamento', verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='adquiriente',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adquirientes', to='catalogos.municipio', verbose_name='municipio'),
        ),
        migrations.AlterField(
            model_name='adquiriente',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adquirientes', to='catalogos.pais', verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='adquiriente',
            name='responsabilidades',
            field=models.ManyToManyField(blank=True, related_name='adquirientes', to='catalogos.responsabilidadfiscal', verbose_name='responsabilidades fiscales'),
        ),
        migrations.AlterField(
            model_name='adquiriente',
            name='tipo_identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adquirientes', to='catalogos.tipoidentificacion', verbose_name='tipo de identificación'),
        ),
        migrations.AlterField(
            model_name='adquiriente',
            name='tipo_organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adquirientes', to='catalogos.tipoorganizacion', verbose_name='tipo de organización'),
        ),
        migrations.AlterField(
            model_name='documentoelectronico',
            name='adquiriente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.adquiriente', verbose_name='adquiriente'),
        ),
    ]
