# Generated by Django 5.1.15 on 2026-06-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_alter_conceptonotacredito_table_and_more'),
        ('documentos', '0006_alter_adquiriente_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adquiriente',
            constraint=models.UniqueConstraint(fields=('tipo_identificacion', 'numero_identificacion'), name='adquiriente_identificacion_unica'),
        ),
    ]
