# Generated by Django 5.1.15 on 2026-09-22 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_documento_respuesta_validado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido')], max_length=20, verbose_name='estado')),
                ('destinatario', models.CharField(max_length=500, verbose_name='destinatario')),
                ('copia', models.CharField(blank=True, max_length=255, verbose_name='copia')),
                ('archivo', models.CharField(max_length=255, verbose_name='archivo')),
                ('tamano', models.PositiveIntegerField(verbose_name='tamaño en bytes')),
                ('contenido', models.JSONField(blank=True, default=list, verbose_name='archivos del zip')),
                ('codigo_envio', models.CharField(blank=True, max_length=100, verbose_name='código de envío')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='documentos.documento', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'notificación de documento',
                'verbose_name_plural': 'notificaciones de documento',
                'db_table': 'doc_documento_notificacion',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
