# Generated by Django 5.1.15 on 2026-06-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_adquiriente_adquiriente_identificacion_unica'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoelectronico',
            name='track_id',
            field=models.CharField(blank=True, help_text='Identificador del envío (ZipKey del Set de Pruebas o trackId), para consultar el estado en la DIAN.', max_length=100, verbose_name='track id DIAN'),
        ),
    ]
