# Generated by Django 5.1.15 on 2026-06-29 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_alter_conceptonotacredito_table_and_more'),
        ('documentos', '0010_rename_linea_a_documento_detalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentodetalle',
            options={'ordering': ['numero_linea'], 'verbose_name': 'detalle de documento', 'verbose_name_plural': 'detalles de documento'},
        ),
        migrations.AlterModelOptions(
            name='documentodetalleimpuesto',
            options={'verbose_name': 'impuesto de detalle', 'verbose_name_plural': 'impuestos de detalle'},
        ),
        migrations.RemoveConstraint(
            model_name='documentodetalle',
            name='linea_numero_unico_por_documento',
        ),
        migrations.AlterField(
            model_name='documentodetalle',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='documentos.documento', verbose_name='documento'),
        ),
        migrations.AlterField(
            model_name='documentodetalle',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='catalogos.unidadmedida', verbose_name='unidad de medida'),
        ),
        migrations.AlterField(
            model_name='documentodetalle',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='cantidad × valor unitario (LineExtensionAmount).', max_digits=18, verbose_name='valor total del detalle'),
        ),
        migrations.AlterField(
            model_name='documentodetalleimpuesto',
            name='detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='documentos.documentodetalle', verbose_name='detalle'),
        ),
        migrations.AlterField(
            model_name='documentodetalleimpuesto',
            name='tributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impuestos_detalle', to='catalogos.tributo', verbose_name='tributo'),
        ),
        migrations.AddConstraint(
            model_name='documentodetalle',
            constraint=models.UniqueConstraint(fields=('documento', 'numero_linea'), name='documento_detalle_numero_unico'),
        ),
    ]
