# Generated by Django 5.1.15 on 2026-06-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0011_alter_documentodetalle_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(choices=[('factura_venta', 'Factura de venta'), ('nota_credito', 'Nota crédito'), ('nota_debito', 'Nota débito'), ('documento_soporte', 'Documento soporte'), ('nomina', 'Nómina electrónica')], help_text='Discriminador interno que define la lógica de generación.', max_length=30, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('codigo_dian', models.CharField(blank=True, help_text='InvoiceTypeCode oficial (01, 02, 91, 92, 05).', max_length=2, verbose_name='código DIAN (InvoiceTypeCode)')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documento',
                'db_table': 'doc_documento_tipo',
                'ordering': ['codigo'],
            },
        ),
    ]
