# Generated by Django 5.1.15 on 2026-06-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0013_documento_tipo_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='numero',
            field=models.CharField(blank=True, help_text='Número del documento (cbc:ID). Si se omite, se arma como prefijo + consecutivo.', max_length=30, verbose_name='número'),
        ),
    ]
