# Generated by Django 5.1.15 on 2026-06-30 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0017_documento_estado_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='origen_llave',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='origen_usuario',
        ),
    ]
