# Generated by Django 5.1.15 on 2026-06-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0018_remove_documento_origen_llave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, help_text='Momento en que la DIAN aceptó el documento.', null=True, verbose_name='fecha y hora de validación DIAN'),
        ),
    ]
