# Generated by Django 5.1.15 on 2026-08-21 20:18

import apps.documentos.models.documento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0022_adquiriente_por_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='ambiente',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Producción'), (2, 'Habilitación (Set de Pruebas)')], default=apps.documentos.models.documento.ambiente_por_defecto, help_text='ProfileExecutionID del XML: 1 producción, 2 habilitación. Se fija al crear el documento y no cambia después.', verbose_name='ambiente DIAN'),
        ),
    ]
