# Generated by Django 5.1.15 on 2026-08-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0024_recalcular_dv_adquiriente'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='envio',
            field=models.CharField(blank=True, choices=[('test_set', 'Set de Pruebas (SendTestSetAsync)'), ('bill_sync', 'Síncrono (SendBillSync)')], help_text='Con qué operación se envió a la DIAN. Decide cómo se consulta después el estado: GetStatusZip para el Set de Pruebas (el track_id es un ZipKey) y GetStatus para el envío síncrono. Vacío mientras no se haya enviado.', max_length=20, verbose_name='operación de envío'),
        ),
    ]
