# Generated by Django 5.1.15 on 2026-08-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0025_documento_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='concepto_correccion',
            field=models.CharField(blank=True, help_text='ResponseCode del DiscrepancyResponse: por qué se corrige el documento referenciado. Los códigos válidos dependen del tipo de nota (ConceptoNotaCredito, ConceptoNotaDebito). Vacío en lo que no es nota.', max_length=2, verbose_name='concepto de corrección'),
        ),
    ]
