# Generated by Django 5.1.15 on 2026-08-26 10:34

import apps.documentos.models.documento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0026_documento_concepto_correccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='hora_emision',
            field=models.TimeField(default=apps.documentos.models.documento.hora_por_defecto, help_text='IssueTime del XML. Si se omite se toma la hora actual, y al firmar se reescribe con la hora de la firma.', verbose_name='hora de emisión'),
        ),
    ]
