# Generated by Django 5.1.15 on 2026-08-26 10:35

import apps.documentos.models.documento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0027_hora_emision_por_defecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='fecha_emision',
            field=models.DateField(default=apps.documentos.models.documento.fecha_por_defecto, help_text='IssueDate del XML. Si se omite se toma la fecha de hoy, que es la única con la que se puede firmar (regla FAD09).', verbose_name='fecha de emisión'),
        ),
    ]
