# Generated by Django 5.1.15 on 2026-08-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0028_fecha_emision_por_defecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='DueDate del XML: hasta cuándo hay plazo para pagar. La DIAN la exige cuando la forma de pago es a crédito; en contado sobra.', null=True, verbose_name='fecha de vencimiento'),
        ),
    ]
