# Generated by Django 5.1.15 on 2026-08-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0029_documento_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='orden_compra',
            field=models.CharField(blank=True, help_text='Número de la orden de compra del adquiriente, si la hubo.', max_length=100, verbose_name='orden de compra'),
        ),
        migrations.AddField(
            model_name='documento',
            name='orden_compra_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de la orden de compra'),
        ),
        migrations.AddField(
            model_name='documentodetalle',
            name='centro_costo',
            field=models.CharField(blank=True, help_text='cbc:AccountingCostCode: a qué centro de costo se imputa.', max_length=50, verbose_name='centro de costo'),
        ),
        migrations.AddField(
            model_name='documentodetalle',
            name='marca',
            field=models.CharField(blank=True, help_text='cbc:BrandName del ítem.', max_length=100, verbose_name='marca'),
        ),
        migrations.AddField(
            model_name='documentodetalle',
            name='modelo',
            field=models.CharField(blank=True, help_text='cbc:ModelName del ítem.', max_length=100, verbose_name='modelo'),
        ),
        migrations.AddField(
            model_name='documentodetalle',
            name='nota',
            field=models.CharField(blank=True, help_text='cbc:Note de la línea: aclaración libre sobre este ítem.', max_length=500, verbose_name='nota de la línea'),
        ),
        migrations.AddField(
            model_name='documentodetalle',
            name='periodo_desde',
            field=models.DateField(blank=True, help_text='cac:InvoicePeriod/cbc:StartDate: para servicios por periodo.', null=True, verbose_name='periodo facturado desde'),
        ),
        migrations.AddField(
            model_name='documentodetalle',
            name='periodo_hasta',
            field=models.DateField(blank=True, help_text='cac:InvoicePeriod/cbc:EndDate.', null=True, verbose_name='periodo facturado hasta'),
        ),
    ]
