# Generated by Django 5.1.15 on 2026-08-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0030_campos_de_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='orden_compra_documento',
            field=models.CharField(blank=True, help_text='cac:DocumentReference/cbc:ID: el soporte de la orden (contrato, acuerdo marco) cuando es distinto del número de la orden.', max_length=100, verbose_name='documento de la orden de compra'),
        ),
        migrations.AddField(
            model_name='documento',
            name='orden_compra_tipo',
            field=models.CharField(blank=True, help_text='cbc:OrderTypeCode: qué clase de orden es (contrato, pedido…), según la codificación que use el comprador.', max_length=20, verbose_name='tipo de la orden de compra'),
        ),
        migrations.AddField(
            model_name='documentodetalle',
            name='periodo_descripcion',
            field=models.CharField(blank=True, help_text="cac:InvoicePeriod/cbc:Description: el periodo en palabras (p. ej. 'Agosto de 2026').", max_length=255, verbose_name='descripción del periodo'),
        ),
        migrations.AddField(
            model_name='documentodetalle',
            name='periodo_descripcion_codigo',
            field=models.CharField(blank=True, help_text='cac:InvoicePeriod/cbc:DescriptionCode.', max_length=20, verbose_name='código de la descripción del periodo'),
        ),
    ]
