# Generated by Django 5.1.15 on 2026-08-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0031_campos_orden_y_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adquiriente',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=100, verbose_name='primer apellido'),
        ),
        migrations.AddField(
            model_name='adquiriente',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='primer nombre'),
        ),
        migrations.AddField(
            model_name='adquiriente',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, verbose_name='segundo apellido'),
        ),
        migrations.AddField(
            model_name='adquiriente',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='segundo nombre'),
        ),
    ]
