# Generated by Django 5.1.15 on 2026-08-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0032_adquiriente_nombre_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='adquiriente',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='cbc:PostalZone de las direcciones del XML.', max_length=10, verbose_name='código postal'),
        ),
    ]
