# Generated by Django 5.1.15 on 2026-08-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0033_adquiriente_codigo_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='cargos_motivo',
            field=models.CharField(blank=True, help_text='cbc:AllowanceChargeReason del cargo global.', max_length=255, verbose_name='motivo de los cargos'),
        ),
        migrations.AddField(
            model_name='documento',
            name='descuentos_motivo',
            field=models.CharField(blank=True, help_text='cbc:AllowanceChargeReason del descuento global.', max_length=255, verbose_name='motivo de los descuentos'),
        ),
        migrations.AddField(
            model_name='documentodetalle',
            name='descuento_motivo',
            field=models.CharField(blank=True, help_text='cbc:AllowanceChargeReason de la línea.', max_length=255, verbose_name='motivo del descuento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='total_descuentos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuentos globales del documento (no los de línea).', max_digits=18, verbose_name='total descuentos'),
        ),
        migrations.AlterField(
            model_name='documentodetalle',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento ya aplicado en el valor total de la línea: el cac:AllowanceCharge lo declara con BaseAmount = valor_total + descuento.', max_digits=18, verbose_name='descuento'),
        ),
    ]
