# Generated by Django 5.1.15 on 2026-08-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0034_descuentos_allowance_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='notificado',
            field=models.BooleanField(default=False, help_text='Si ya se le entregó el documento al comprador. Lo marca la acción `notificar`; mientras el envío por correo no exista, significa que el paquete se armó y se entregó a quien lo pidió.', verbose_name='notificado al adquiriente'),
        ),
    ]
