# Generated by Django 5.1.15 on 2026-08-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0036_nota_ajuste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='ambiente',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Producción'), (2, 'Habilitación')], help_text='ProfileExecutionID del XML: 1 producción, 2 habilitación. Se hereda del emisor al crear y se sella al firmar; no lo decide el ajuste del servidor.', verbose_name='ambiente DIAN'),
        ),
    ]
