# Generated by Django 5.1.15 on 2026-08-31 10:00

from django.db import migrations, models

CODIGO = "documento_equivalente_pos"


def crear_tipo(apps, schema_editor):
    """Siembra el tipo del documento equivalente P.O.S.

    Mismo criterio que ``0013_documento_tipo_fk``: el catálogo es de datos, no
    de código, así que la fila la crea la migración y no un fixture que haya que
    acordarse de cargar. El ``codigo_dian`` "20" lo exige la regla DEAD12b.
    """
    DocumentoTipo = apps.get_model("documentos", "DocumentoTipo")
    DocumentoTipo.objects.update_or_create(
        codigo=CODIGO,
        defaults={"nombre": "Documento equivalente P.O.S.", "codigo_dian": "20"},
    )


def borrar_tipo(apps, schema_editor):
    """Solo si nadie lo usa: un tipo con documentos emitidos no se borra."""
    DocumentoTipo = apps.get_model("documentos", "DocumentoTipo")
    DocumentoTipo.objects.filter(codigo=CODIGO, documentos__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0037_alter_documento_ambiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentotipo',
            name='codigo',
            field=models.CharField(choices=[('factura_venta', 'Factura de venta'), ('nota_credito', 'Nota crédito'), ('nota_debito', 'Nota débito'), ('documento_soporte', 'Documento soporte'), ('nota_ajuste', 'Nota de ajuste al documento soporte'), ('nomina', 'Nómina electrónica'), ('documento_equivalente_pos', 'Documento equivalente P.O.S.')], help_text='Discriminador interno que define la lógica de generación.', max_length=30, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='documentotipo',
            name='codigo_dian',
            field=models.CharField(blank=True, help_text='InvoiceTypeCode oficial (01, 02, 91, 92, 05, 20).', max_length=2, verbose_name='código DIAN (InvoiceTypeCode)'),
        ),
        migrations.RunPython(crear_tipo, borrar_tipo),
    ]
