# Generated by Django 5.1.15 on 2026-08-31 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0038_documento_equivalente_pos'),
        ('emisores', '0024_documento_equivalente_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('placa', models.CharField(help_text='Placa de inventario de la caja. Va en el par `PlacaCaja`.', max_length=50, verbose_name='placa de la caja')),
                ('ubicacion', models.CharField(help_text='Dónde está la caja dentro del establecimiento. Va en el par `UbicaciónCaja` —con tilde, que es el literal del anexo—.', max_length=255, verbose_name='ubicación de la caja')),
                ('tipo', models.CharField(help_text="Va en el par `TipoCaja`. El anexo no da lista de valores; la ejemplificación oficial usa texto libre ('Caja de apoyo').", max_length=100, verbose_name='tipo de caja')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_venta', to='emisores.emisor', verbose_name='emisor')),
            ],
            options={
                'verbose_name': 'caja de venta',
                'verbose_name_plural': 'cajas de venta',
                'db_table': 'doc_caja_venta',
                'ordering': ['emisor', 'placa'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('cajero', models.CharField(help_text='Nombres y apellidos del cajero o vendedor (par `Cajero`).', max_length=200, verbose_name='cajero')),
                ('codigo_venta', models.CharField(help_text='Identificador interno de la transacción (par `CódigoVenta`, con tilde).', max_length=50, verbose_name='código de la venta')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Par `SubTotal`. Si se deja vacío se emite el `valor_bruto` del documento. Se admite informarlo aparte porque la ejemplificación oficial trae ahí un importe distinto del LineExtensionAmount y el anexo no aclara la diferencia.', max_digits=15, null=True, verbose_name='subtotal de la venta')),
                ('comprador_codigo', models.CharField(blank=True, help_text='Documento de identidad del comprador. Vacío emite el del adquiriente del documento.', max_length=50, verbose_name='código del comprador')),
                ('comprador_nombres', models.CharField(blank=True, help_text='Vacío emite el nombre del adquiriente del documento.', max_length=200, verbose_name='nombres del comprador')),
                ('comprador_puntos', models.PositiveIntegerField(default=0, help_text='Puntos del programa de fidelización. Cero si no hay programa: el par es obligatorio y omitirlo es un rechazo.', verbose_name='puntos acumulados')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.cajaventa', verbose_name='caja de venta')),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='documentos.documento', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'datos P.O.S. del documento',
                'verbose_name_plural': 'datos P.O.S. de los documentos',
                'db_table': 'doc_documento_pos',
            },
        ),
        migrations.AddConstraint(
            model_name='cajaventa',
            constraint=models.UniqueConstraint(fields=('emisor', 'placa'), name='caja_placa_unica_por_emisor'),
        ),
    ]
