# Generated by Django 5.1.15 on 2026-08-31 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0040_pos_caja_venta'),
        ('emisores', '0024_documento_equivalente_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivoArchivoDocumentoEquivalente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('valor', models.PositiveIntegerField(default=0, verbose_name='último consecutivo usado')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consecutivos_archivo_documento_equivalente', to='emisores.emisor', verbose_name='emisor')),
            ],
            options={
                'verbose_name': 'consecutivo de archivos de documento equivalente',
                'verbose_name_plural': 'consecutivos de archivos de documento equivalente',
                'db_table': 'doc_consecutivo_archivo_de',
                'ordering': ['-anio'],
                'constraints': [models.UniqueConstraint(fields=('emisor', 'anio'), name='consecutivo_archivo_de_unico_por_anio')],
            },
        ),
    ]
