# Generated by Django 5.1.15 on 2026-08-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0042_notas_ajuste_documento_equivalente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentotipo',
            name='codigo',
            field=models.CharField(choices=[('factura_venta', 'Factura de venta'), ('nota_credito', 'Nota crédito'), ('nota_debito', 'Nota débito'), ('documento_soporte', 'Documento soporte'), ('nota_ajuste', 'Nota de ajuste al documento soporte'), ('nomina', 'Nómina electrónica'), ('documento_equivalente_pos', 'Documento equivalente P.O.S.'), ('nota_ajuste_de_credito', 'Nota de ajuste crédito al documento equivalente'), ('nota_ajuste_de_debito', 'Nota de ajuste débito al documento equivalente')], help_text='Discriminador interno que define la lógica de generación.', max_length=30, unique=True, verbose_name='código'),
        ),
    ]
