# Generated by Django 5.1.15 on 2026-09-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_datos_nomina'),
        ('documentos', '0044_pos_caja_en_el_documento'),
        ('emisores', '0027_quitar_consecutivo_actual'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['emisor', '-fecha_emision', '-consecutivo'], name='doc_emisor_recientes'),
        ),
    ]
