# Generated by Django 5.1.15 on 2026-09-08 19:58

import apps.seguridad.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('emisores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('nombre_corto', models.CharField(max_length=255, null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Indica si el usuario puede entrar al sitio de administración.', verbose_name='acceso al admin')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la cuenta está activa. Desmarcar en lugar de borrar.', verbose_name='activo')),
                ('is_verified', models.BooleanField(default=False, help_text='El usuario confirmó su correo. Sin esto no puede iniciar sesión.', verbose_name='correo verificado')),
                ('emisores', models.ManyToManyField(blank=True, help_text='Emisores cuyos datos puede consultar y operar el usuario.', related_name='usuarios', to='emisores.emisor', verbose_name='emisores')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'seg_usuario',
                'ordering': ('email',),
            },
            managers=[
                ('objects', apps.seguridad.managers.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='LlaveApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(help_text="Identifica la integración, p. ej. 'ERP producción'.", max_length=150, verbose_name='nombre')),
                ('prefijo', models.CharField(editable=False, help_text='Identificador público de la llave (no es secreto).', max_length=8, unique=True, verbose_name='prefijo')),
                ('clave_hash', models.CharField(editable=False, max_length=128, verbose_name='hash de la clave')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('expira_en', models.DateTimeField(blank=True, null=True, verbose_name='expira en')),
                ('ultimo_uso_en', models.DateTimeField(blank=True, null=True, verbose_name='último uso en')),
                ('usuario', models.ForeignKey(help_text='Persona en cuyo nombre actúa la llave.', on_delete=django.db.models.deletion.CASCADE, related_name='llaves_api', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'llave de API',
                'verbose_name_plural': 'llaves de API',
                'db_table': 'seg_llave_api',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MfaDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('metodo', models.CharField(choices=[('totp', 'Aplicación autenticadora'), ('correo', 'Código por correo')], max_length=20, verbose_name='método')),
                ('hash_codigo', models.CharField(blank=True, max_length=64, verbose_name='hash del código')),
                ('intentos', models.PositiveSmallIntegerField(default=0, verbose_name='intentos')),
                ('consumido', models.BooleanField(default=False, verbose_name='consumido')),
                ('expira', models.DateTimeField(verbose_name='expira')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_mfa', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'desafío de segundo factor',
                'verbose_name_plural': 'desafíos de segundo factor',
                'db_table': 'seg_mfa_desafio',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MfaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('metodo', models.CharField(choices=[('totp', 'Aplicación autenticadora'), ('correo', 'Código por correo')], max_length=20, verbose_name='método')),
                ('secreto', models.CharField(blank=True, max_length=500, verbose_name='secreto cifrado')),
                ('activo', models.BooleanField(default=False, verbose_name='activo')),
                ('ultimo_contador', models.BigIntegerField(blank=True, null=True, verbose_name='último contador TOTP')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'segundo factor',
                'verbose_name_plural': 'segundos factores',
                'db_table': 'seg_mfa_usuario',
            },
        ),
        migrations.CreateModel(
            name='MfaCodigoRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('hash_codigo', models.CharField(max_length=64, verbose_name='hash del código')),
                ('usado_en', models.DateTimeField(blank=True, null=True, verbose_name='usado en')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_respaldo', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'código de respaldo',
                'verbose_name_plural': 'códigos de respaldo',
                'db_table': 'seg_mfa_codigo_respaldo',
                'indexes': [models.Index(fields=['usuario', 'hash_codigo'], name='seg_mfa_cod_usuario_2ecda0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MfaDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('hash_token', models.CharField(max_length=64, verbose_name='hash del token')),
                ('agente', models.CharField(blank=True, max_length=500, verbose_name='navegador')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True, verbose_name='último uso')),
                ('expira', models.DateTimeField(verbose_name='expira')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_mfa', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'dispositivo recordado',
                'verbose_name_plural': 'dispositivos recordados',
                'db_table': 'seg_mfa_dispositivo',
                'ordering': ['-ultimo_uso'],
                'indexes': [models.Index(fields=['usuario', 'hash_token'], name='seg_mfa_dis_usuario_2591a4_idx')],
            },
        ),
    ]
