# Generated by Django 5.1.15 on 2026-06-24 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0001_initial'),
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlaveApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(help_text="Identifica la integración, p. ej. 'ERP producción'.", max_length=150, verbose_name='nombre')),
                ('prefijo', models.CharField(editable=False, help_text='Identificador público de la llave (no es secreto).', max_length=8, unique=True, verbose_name='prefijo')),
                ('clave_hash', models.CharField(editable=False, max_length=128, verbose_name='hash de la clave')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('expira_en', models.DateTimeField(blank=True, null=True, verbose_name='expira en')),
                ('ultimo_uso_en', models.DateTimeField(blank=True, null=True, verbose_name='último uso en')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llaves_api', to='emisores.emisor', verbose_name='emisor')),
            ],
            options={
                'verbose_name': 'llave de API',
                'verbose_name_plural': 'llaves de API',
                'ordering': ['-creado_en'],
            },
        ),
    ]
