# Generated by Django 5.1.15 on 2026-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llaveapi',
            name='alcance_global',
            field=models.BooleanField(default=False, help_text='Alcanza todos los emisores, como el staff. Exige dueño staff y vencimiento de 90 días como máximo.', verbose_name='alcance global'),
        ),
    ]
