# Generated by Django 5.1.15 on 2026-06-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_usuario_cuenta'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='llaveapi',
            table='seg_llaveapi',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='seg_usuario',
        ),
    ]
