# Generated by Django 5.1.15 on 2026-06-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_alter_llaveapi_table_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='llaveapi',
            table='seg_llave_api',
        ),
    ]
