# Generated by Django 5.1.15 on 2026-08-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0007_remove_usuario_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llaveapi',
            name='emisor',
        ),
    ]
