# Generated by Django 5.1.15 on 2026-09-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0009_usuario_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombres',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_corto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
