# Generated by Django 5.1.15 on 2026-09-08 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0011_limpiar_email_verificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MfaDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('metodo', models.CharField(choices=[('totp', 'Aplicación autenticadora'), ('correo', 'Código por correo')], max_length=20, verbose_name='método')),
                ('hash_codigo', models.CharField(blank=True, max_length=64, verbose_name='hash del código')),
                ('intentos', models.PositiveSmallIntegerField(default=0, verbose_name='intentos')),
                ('consumido', models.BooleanField(default=False, verbose_name='consumido')),
                ('expira', models.DateTimeField(verbose_name='expira')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_mfa', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'desafío de segundo factor',
                'verbose_name_plural': 'desafíos de segundo factor',
                'db_table': 'seg_mfa_desafio',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MfaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('metodo', models.CharField(choices=[('totp', 'Aplicación autenticadora'), ('correo', 'Código por correo')], max_length=20, verbose_name='método')),
                ('secreto', models.CharField(blank=True, max_length=500, verbose_name='secreto cifrado')),
                ('activo', models.BooleanField(default=False, verbose_name='activo')),
                ('ultimo_contador', models.BigIntegerField(blank=True, null=True, verbose_name='último contador TOTP')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'segundo factor',
                'verbose_name_plural': 'segundos factores',
                'db_table': 'seg_mfa_usuario',
            },
        ),
        migrations.CreateModel(
            name='MfaCodigoRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('hash_codigo', models.CharField(max_length=64, verbose_name='hash del código')),
                ('usado_en', models.DateTimeField(blank=True, null=True, verbose_name='usado en')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_respaldo', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'código de respaldo',
                'verbose_name_plural': 'códigos de respaldo',
                'db_table': 'seg_mfa_codigo_respaldo',
                'indexes': [models.Index(fields=['usuario', 'hash_codigo'], name='seg_mfa_cod_usuario_2ecda0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MfaDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('hash_token', models.CharField(max_length=64, verbose_name='hash del token')),
                ('agente', models.CharField(blank=True, max_length=500, verbose_name='navegador')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True, verbose_name='último uso')),
                ('expira', models.DateTimeField(verbose_name='expira')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_mfa', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'dispositivo recordado',
                'verbose_name_plural': 'dispositivos recordados',
                'db_table': 'seg_mfa_dispositivo',
                'ordering': ['-ultimo_uso'],
                'indexes': [models.Index(fields=['usuario', 'hash_token'], name='seg_mfa_dis_usuario_2591a4_idx')],
            },
        ),
    ]
