# Generated by Django 5.1.15 on 2026-10-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoReclamo',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'concepto de reclamo',
                'verbose_name_plural': 'conceptos de reclamo',
                'db_table': 'cat_concepto_reclamo',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventoRadian',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'evento RADIAN',
                'verbose_name_plural': 'eventos RADIAN',
                'db_table': 'cat_evento_radian',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Festivo',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha', models.DateField(unique=True, verbose_name='fecha')),
            ],
            options={
                'verbose_name': 'festivo',
                'verbose_name_plural': 'festivos',
                'db_table': 'cat_festivo',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
    ]
