# Generated by Django 5.1.15 on 2026-06-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conceptonotacredito',
            table='cat_conceptonotacredito',
        ),
        migrations.AlterModelTable(
            name='conceptonotadebito',
            table='cat_conceptonotadebito',
        ),
        migrations.AlterModelTable(
            name='departamento',
            table='cat_departamento',
        ),
        migrations.AlterModelTable(
            name='formapago',
            table='cat_formapago',
        ),
        migrations.AlterModelTable(
            name='mediopago',
            table='cat_mediopago',
        ),
        migrations.AlterModelTable(
            name='moneda',
            table='cat_moneda',
        ),
        migrations.AlterModelTable(
            name='municipio',
            table='cat_municipio',
        ),
        migrations.AlterModelTable(
            name='pais',
            table='cat_pais',
        ),
        migrations.AlterModelTable(
            name='responsabilidadfiscal',
            table='cat_responsabilidadfiscal',
        ),
        migrations.AlterModelTable(
            name='tipofactura',
            table='cat_tipofactura',
        ),
        migrations.AlterModelTable(
            name='tipoidentificacion',
            table='cat_tipoidentificacion',
        ),
        migrations.AlterModelTable(
            name='tipoorganizacion',
            table='cat_tipoorganizacion',
        ),
        migrations.AlterModelTable(
            name='tributo',
            table='cat_tributo',
        ),
        migrations.AlterModelTable(
            name='unidadmedida',
            table='cat_unidadmedida',
        ),
    ]
