# Generated by Django 5.1.15 on 2026-09-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_datos_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='El de la cabecera. Respalda el cbc:PostalZone del XML cuando el emisor o el adquiriente no informan el suyo.', max_length=6, verbose_name='código postal'),
        ),
    ]
