# Generated by Django 5.1.15 on 2026-06-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_conceptonotacredito_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipofactura',
            table='cat_tipo_factura',
        ),
    ]
