# Generated by Django 5.1.15 on 2026-06-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_alter_tipofactura_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conceptonotacredito',
            table='cat_concepto_nota_credito',
        ),
        migrations.AlterModelTable(
            name='conceptonotadebito',
            table='cat_concepto_nota_debito',
        ),
        migrations.AlterModelTable(
            name='formapago',
            table='cat_forma_pago',
        ),
        migrations.AlterModelTable(
            name='mediopago',
            table='cat_medio_pago',
        ),
        migrations.AlterModelTable(
            name='responsabilidadfiscal',
            table='cat_responsabilidad_fiscal',
        ),
        migrations.AlterModelTable(
            name='tipoidentificacion',
            table='cat_tipo_identificacion',
        ),
        migrations.AlterModelTable(
            name='tipoorganizacion',
            table='cat_tipo_organizacion',
        ),
        migrations.AlterModelTable(
            name='unidadmedida',
            table='cat_unidad_medida',
        ),
    ]
