# Generated by Django 5.1.15 on 2026-08-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_alter_conceptonotacredito_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'periodo de nómina',
                'verbose_name_plural': 'periodos de nómina',
                'db_table': 'cat_periodo_nomina',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTipoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'subtipo de trabajador',
                'verbose_name_plural': 'subtipos de trabajador',
                'db_table': 'cat_subtipo_trabajador',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de contrato',
                'verbose_name_plural': 'tipos de contrato',
                'db_table': 'cat_tipo_contrato',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de trabajador',
                'verbose_name_plural': 'tipos de trabajador',
                'db_table': 'cat_tipo_trabajador',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
    ]
